// apps/nihongo-angular/src/app/features/mock-exam/mock-exam-list-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import type { MockExamTemplate } from '../../core/models/api.models';

@Component({
  selector: 'app-mock-exam-list-page',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './mock-exam-list-page.component.html',
  styleUrl: './mock-exam-list-page.component.scss',
})
export class MockExamListPageComponent {
  private readonly api = inject(ApiService);

  readonly templates = signal<MockExamTemplate[]>([]);
  readonly loading = signal(true);
  readonly error = signal(false);

  constructor() {
    void this.api
      .getMockExamTemplates()
      .then((data) => {
        this.templates.set(data);
        this.loading.set(false);
      })
      .catch(() => {
        this.error.set(true);
        this.loading.set(false);
      });
  }
}

<section class="container mock-exam-page">
  <header class="mock-exam-header">
    <h2 class="view-title">Thi thử JLPT</h2>
    <p class="subtitle">
      Làm bài theo format thi thật — có giới hạn thời gian, nộp bài một lần, sau đó xem đáp án chi tiết.
    </p>
  </header>

  @if (loading()) {
    <div class="empty-state glass-panel">
      <p>Đang tải đề thi...</p>
    </div>
  } @else if (error()) {
    <div class="empty-state glass-panel">
      <p>Không tải được danh sách đề thi. Hãy kiểm tra backend.</p>
    </div>
  } @else {
    <div class="mock-exam-grid">
      @for (tpl of templates(); track tpl.level) {
        <article class="mock-exam-card glass-panel">
          <span class="level-badge">{{ tpl.level.toUpperCase() }}</span>
          <h3>{{ tpl.title }}</h3>
          <p>{{ tpl.description }}</p>
          <ul class="mock-exam-meta">
            <li>⏱ {{ tpl.durationMinutes }} phút</li>
            <li>📝 {{ tpl.questionCount }} câu</li>
          </ul>
          <a [routerLink]="['/mock-exam', tpl.level]" class="btn btn-primary">Bắt đầu thi</a>
        </article>
      }
    </div>
  }

  <section class="mock-exam-notes glass-panel">
    <h3>Lưu ý khi thi</h3>
    <ul>
      <li>Không hiện đáp án trong lúc làm bài — giống kỳ thi thật.</li>
      <li>Phần Nghe: audio TTS tự phát, nghe lại tối đa 2 lần/câu.</li>
      <li>Có thể chuyển qua lại giữa các câu trước khi nộp bài.</li>
      <li>Hết giờ hệ thống tự nộp bài với các câu đã chọn.</li>
    </ul>
  </section>
</section>

// apps/nihongo-web/src/views/MockExamListPage.tsx
'use client';

import Link from 'next/link';
import { useMockExamTemplatesQuery } from '../hooks/queries';
import './MockExam.css';

export default function MockExamListPage() {
  const { data: templates = [], isLoading: loading, isError } = useMockExamTemplatesQuery();

  return (
    <div className="container mock-exam-page">
      <header className="mock-exam-header">
        <h2 className="view-title">Thi thử JLPT</h2>
        <p className="mock-exam-subtitle">
          Làm bài theo format thi thật — có giới hạn thời gian, nộp bài một lần, sau đó xem đáp án chi tiết.
        </p>
      </header>

      {loading ? (
        <div className="empty-state glass-panel">
          <p>Đang tải đề thi...</p>
        </div>
      ) : isError ? (
        <div className="empty-state glass-panel">
          <p>Không tải được danh sách đề thi. Hãy kiểm tra backend.</p>
        </div>
      ) : (
        <div className="mock-exam-grid">
          {templates.map((tpl) => (
            <article key={tpl.level} className="mock-exam-card glass-panel">
              <span className={`mock-exam-level-badge level-${tpl.level}`}>{tpl.level.toUpperCase()}</span>
              <h3>{tpl.title}</h3>
              <p>{tpl.description}</p>
              <ul className="mock-exam-meta">
                <li>⏱ {tpl.durationMinutes} phút</li>
                <li>📝 {tpl.totalQuestions} câu</li>
                <li>📖 {tpl.scope ?? `Minna Bài ${tpl.lessonRange}`}</li>
              </ul>
              <Link href={`/mock-exam/${tpl.level}`} className="btn btn-primary mock-exam-start-btn">
                Bắt đầu thi
              </Link>
            </article>
          ))}
        </div>
      )}

      <section className="mock-exam-notes glass-panel">
        <h3>Lưu ý khi thi</h3>
        <ul>
          <li>Không hiện đáp án trong lúc làm bài — giống kỳ thi thật.</li>
          <li>Phần <strong>Nghe</strong>: audio TTS tự phát, nghe lại tối đa 2 lần/câu.</li>
          <li>Có thể chuyển qua lại giữa các câu trước khi nộp bài.</li>
          <li>Hết giờ hệ thống tự nộp bài với các câu đã chọn.</li>
          <li>Sau khi nộp, vào trang <strong>Đáp án &amp; giải thích</strong> để ôn lại.</li>
        </ul>
      </section>
    </div>
  );
}
