// apps/nihongo-angular/src/app/features/mock-exam/mock-exam-answers-page.component.ts
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { playJapanese } from '../../core/utils/speech.util';
import {
  clearMockExamResult,
  loadMockExamResult,
  type MockExamResult,
  type MockExamReviewItem,
} from '../../core/utils/mock-exam.util';

type ReviewFilter = 'all' | 'wrong' | 'correct';

@Component({
  selector: 'app-mock-exam-answers-page',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './mock-exam-answers-page.component.html',
  styleUrl: './mock-exam-answers-page.component.scss',
})
export class MockExamAnswersPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  readonly level = signal('');
  readonly result = signal<MockExamResult | null>(null);
  readonly filter = signal<ReviewFilter>('all');

  readonly filteredReview = computed((): MockExamReviewItem[] => {
    const res = this.result();
    if (!res) return [];
    if (this.filter() === 'wrong') return res.review.filter((r) => !r.isCorrect);
    if (this.filter() === 'correct') return res.review.filter((r) => r.isCorrect);
    return res.review;
  });

  readonly wrongCount = computed(() => {
    const res = this.result();
    return res ? res.total - res.correctCount : 0;
  });

  ngOnInit(): void {
    const level = this.route.snapshot.paramMap.get('level') ?? '';
    this.level.set(level);

    const navState = history.state?.['result'] as MockExamResult | undefined;
    const saved = navState ?? loadMockExamResult();

    if (!saved || (level && saved.level !== level)) {
      void this.router.navigate(['/mock-exam']);
      return;
    }
    this.result.set(saved);
  }

  questionNumber(item: MockExamReviewItem): number {
    const res = this.result();
    if (!res) return 0;
    return res.review.findIndex((r) => r.id === item.id) + 1;
  }

  playAudio(text: string): void {
    playJapanese(text);
  }

  clearAndNavigate(): void {
    clearMockExamResult();
  }
}

@if (!result()) {
  <section class="container mock-exam-page">
    <div class="empty-state glass-panel">
      <p>Đang tải kết quả...</p>
    </div>
  </section>
} @else {
  <section class="container mock-exam-page mock-exam-answers">
    <header class="mock-exam-header">
      <h2 class="view-title">Đáp án &amp; kết quả</h2>
      <p class="subtitle">{{ result()!.title }}</p>
    </header>

    <section class="score-summary glass-panel">
      <div class="score-circle" [class.passed]="result()!.passed" [class.failed]="!result()!.passed">
        <span class="score-percent">{{ result()!.percent }}%</span>
        <span class="score-label">{{ result()!.correctCount }}/{{ result()!.total }} đúng</span>
      </div>
      <div class="score-details">
        <h3>{{ result()!.passed ? '🎉 Đạt đề thử!' : '📚 Cần ôn thêm' }}</h3>
        <p>Ngưỡng gợi ý: {{ result()!.passThreshold }}% · Bạn đạt {{ result()!.percent }}%</p>
        <div class="section-scores">
          @for (sec of result()!.sectionScores; track sec.sectionId) {
            <div class="section-score-item">
              <strong>{{ sec.sectionName }}</strong>
              <span>{{ sec.correct }}/{{ sec.total }}</span>
            </div>
          }
        </div>
      </div>
    </section>

    <div class="answers-filter-bar">
      <button type="button" class="filter-btn" [class.active]="filter() === 'all'" (click)="filter.set('all')">
        Tất cả ({{ result()!.total }})
      </button>
      <button type="button" class="filter-btn" [class.active]="filter() === 'wrong'" (click)="filter.set('wrong')">
        Sai ({{ wrongCount() }})
      </button>
      <button type="button" class="filter-btn" [class.active]="filter() === 'correct'" (click)="filter.set('correct')">
        Đúng ({{ result()!.correctCount }})
      </button>
    </div>

    <div class="answers-list">
      @for (item of filteredReview(); track item.id) {
        <article class="answer-card glass-panel" [class.correct]="item.isCorrect" [class.wrong]="!item.isCorrect">
          <div class="answer-card-head">
            <span class="answer-badge">{{ item.sectionName }} · Câu {{ questionNumber(item) }}</span>
            <span class="answer-status" [class.ok]="item.isCorrect" [class.bad]="!item.isCorrect">
              {{ item.isCorrect ? '✓ Đúng' : '✗ Sai' }}
            </span>
          </div>

          <p class="answer-question">{{ item.question }}</p>

          @if (item.type === 'listening' && item.audioText) {
            <button type="button" class="btn btn-outline" (click)="playAudio(item.audioText!)">🔊 Nghe lại</button>
          }

          @if ((item.type === 'multiple_choice' || item.type === 'listening') && item.options?.length) {
            <ul class="answer-options-review">
              @for (opt of item.options!; track opt) {
                <li
                  [class.opt-correct]="opt === item.correctAnswer"
                  [class.opt-wrong]="opt === item.userAnswer && !item.isCorrect"
                >
                  {{ opt }}
                  @if (opt === item.correctAnswer) { ✓ }
                  @if (opt === item.userAnswer && !item.isCorrect) { (bạn chọn) }
                </li>
              }
            </ul>
          }

          @if (item.type === 'fill_in_blank') {
            <div class="answer-fill-review">
              <p>Bạn trả lời: <strong>{{ item.userAnswer || '(bỏ trống)' }}</strong></p>
              <p>Đáp án đúng: <strong class="text-correct">{{ item.correctAnswer }}</strong></p>
            </div>
          }
        </article>
      }
    </div>

    <div class="footer-actions">
      <a [routerLink]="['/mock-exam', result()!.level]" class="btn btn-primary" (click)="clearAndNavigate()">
        Làm đề mới
      </a>
      <a routerLink="/mock-exam" class="btn btn-outline">Chọn đề khác</a>
      <a routerLink="/vocab-review" class="btn btn-outline">Bảng từ sai</a>
    </div>
  </section>
}

// apps/nihongo-web/src/views/MockExamAnswersPage.tsx
'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import {
  clearMockExamResult,
  loadMockExamResult,
  type MockExamResult,
  type MockExamReviewItem,
} from '../utils/mockExam';
import { importWrongItemsFromReview } from '../utils/mistakeVocab';
import ListeningPlayer from '../components/ListeningPlayer';
import './MockExam.css';

type ReviewFilter = 'all' | 'wrong' | 'correct';

export default function MockExamAnswersPage() {
  const params = useParams();
  const level = String(params?.level ?? '');
  const router = useRouter();
  const [result, setResult] = useState<MockExamResult | null>(null);
  const [filter, setFilter] = useState<ReviewFilter>('all');
  const [savedWrongCount, setSavedWrongCount] = useState(0);
  const importedRef = useRef(false);

  useEffect(() => {
    const saved = loadMockExamResult();
    if (!saved || (level && saved.level !== level)) {
      router.replace('/mock-exam');
      return;
    }
    setResult(saved);

    if (!importedRef.current) {
      importedRef.current = true;
      const wrongItems = saved.review.filter((r) => !r.isCorrect);
      const added = importWrongItemsFromReview(wrongItems);
      setSavedWrongCount(added);
    }
  }, [level, router]);

  const filteredReview = useMemo((): MockExamReviewItem[] => {
    if (!result) return [];
    if (filter === 'wrong') return result.review.filter((r) => !r.isCorrect);
    if (filter === 'correct') return result.review.filter((r) => r.isCorrect);
    return result.review;
  }, [result, filter]);

  if (!result) {
    return (
      <div className="container mock-exam-page">
        <div className="empty-state glass-panel">
          <p>Đang tải kết quả...</p>
        </div>
      </div>
    );
  }

  const wrongCount = result.total - result.correctCount;

  return (
    <div className="container mock-exam-page mock-exam-answers">
      <header className="mock-exam-header">
        <h2 className="view-title">Đáp án &amp; kết quả</h2>
        <p className="mock-exam-subtitle">{result.title}</p>
      </header>

      <section className="mock-exam-score-summary glass-panel">
        <div className={`score-circle ${result.passed ? 'passed' : 'failed'}`}>
          <span className="score-percent">{result.percent}%</span>
          <span className="score-label">
            {result.correctCount}/{result.total} đúng
          </span>
        </div>
        <div className="score-details">
          <h3>{result.passed ? '🎉 Đạt đề thử!' : '📚 Cần ôn thêm'}</h3>
          <p>
            Ngưỡng gợi ý: {result.passThreshold}% · Bạn đạt {result.percent}%
          </p>
          <div className="section-scores">
            {result.sectionScores.map((sec) => (
              <div key={sec.sectionId} className="section-score-item">
                <strong>{sec.sectionName}</strong>
                <span>
                  {sec.correct}/{sec.total}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {savedWrongCount > 0 && (
        <p className="mock-exam-saved-wrong glass-panel">
          Đã lưu <strong>{savedWrongCount}</strong> từ sai vào bảng ôn.{' '}
          <Link href="/vocab-review">Ôn ngay →</Link>
        </p>
      )}

      <div className="answers-filter-bar">
        <button
          type="button"
          className={`filter-btn ${filter === 'all' ? 'active' : ''}`}
          onClick={() => setFilter('all')}
        >
          Tất cả ({result.total})
        </button>
        <button
          type="button"
          className={`filter-btn ${filter === 'wrong' ? 'active' : ''}`}
          onClick={() => setFilter('wrong')}
        >
          Sai ({wrongCount})
        </button>
        <button
          type="button"
          className={`filter-btn ${filter === 'correct' ? 'active' : ''}`}
          onClick={() => setFilter('correct')}
        >
          Đúng ({result.correctCount})
        </button>
      </div>

      <div className="answers-list">
        {filteredReview.map((item, index) => (
          <article
            key={item.id}
            className={`answer-card glass-panel ${item.isCorrect ? 'correct' : 'wrong'}`}
          >
            <div className="answer-card-head">
              <span className="answer-badge">
                {item.sectionName} · Câu {result.review.findIndex((r) => r.id === item.id) + 1}
              </span>
              <span className={`answer-status ${item.isCorrect ? 'ok' : 'bad'}`}>
                {item.isCorrect ? '✓ Đúng' : '✗ Sai'}
              </span>
            </div>

            <p className="answer-question">{item.question}</p>

            {item.type === 'listening' && item.audioText && (
              <ListeningPlayer audioText={item.audioText} autoPlay={false} showText unlimited />
            )}

            {(item.type === 'multiple_choice' || item.type === 'listening') &&
              item.options && item.options.length > 0 && (
              <ul className="answer-options-review">
                {item.options.map((opt) => {
                  const isCorrect = opt === item.correctAnswer;
                  const isUser = opt === item.userAnswer;
                  let cls = '';
                  if (isCorrect) cls = 'opt-correct';
                  else if (isUser && !item.isCorrect) cls = 'opt-wrong';
                  return (
                    <li key={`${item.id}-${index}-${opt}`} className={cls}>
                      {opt}
                      {isCorrect && ' ✓'}
                      {isUser && !item.isCorrect && ' (bạn chọn)'}
                    </li>
                  );
                })}
              </ul>
            )}

            {item.type === 'fill_in_blank' && (
              <div className="answer-fill-review">
                <p>
                  Bạn trả lời:{' '}
                  <strong>{item.userAnswer || '(bỏ trống)'}</strong>
                </p>
                <p>
                  Đáp án đúng: <strong className="text-correct">{item.correctAnswer}</strong>
                </p>
              </div>
            )}

            {item.lessonNumber && (
              <p className="answer-lesson-hint">
                Ôn lại:{' '}
                <Link href="/vocab">Minna Bài {item.lessonNumber}</Link>
                {' · '}
                <Link href="/grammar">Ngữ pháp</Link>
                {item.sectionId === 'kanji' && (
                  <>
                    {' · '}
                    <Link href="/kanji">Kanji</Link>
                  </>
                )}
                {item.sectionId === 'listening' && (
                  <>
                    {' · '}
                    <Link href="/vocab">Từ vựng</Link>
                  </>
                )}
              </p>
            )}
          </article>
        ))}
      </div>

      <div className="mock-exam-footer-actions">
        <Link
          href={`/mock-exam/${result.level}`}
          className="btn btn-primary"
          onClick={() => clearMockExamResult()}
        >
          Làm đề mới
        </Link>
        <Link href="/mock-exam" className="btn btn-outline">
          Chọn đề khác
        </Link>
        <Link href="/vocab-review" className="btn btn-outline">
          Bảng từ sai
        </Link>
        <Link href="/jlpt" className="btn btn-outline">
          Lộ trình JLPT
        </Link>
      </div>
    </div>
  );
}
