// apps/nihongo-angular/src/app/features/mock-exam/mock-exam-take-page.component.ts
import { Component, computed, effect, inject, OnDestroy, signal } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { playJapanese } from '../../core/utils/speech.util';
import {
  formatTimer,
  parseMockExamResult,
  parseMockExamSession,
  saveMockExamResult,
  type MockExamQuestion,
  type MockExamSession,
} from '../../core/utils/mock-exam.util';

@Component({
  selector: 'app-mock-exam-take-page',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './mock-exam-take-page.component.html',
  styleUrl: './mock-exam-take-page.component.scss',
})
export class MockExamTakePageComponent implements OnDestroy {
  private readonly api = inject(ApiService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  private timerId: ReturnType<typeof setInterval> | null = null;
  private submitted = false;

  readonly level = signal('');
  readonly exam = signal<MockExamSession | null>(null);
  readonly error = signal('');
  readonly loading = signal(true);
  readonly submitting = signal(false);
  readonly currentIndex = signal(0);
  readonly answers = signal<Record<string, string>>({});
  readonly timeLeft = signal(0);
  readonly confirmSubmit = signal(false);

  readonly questions = computed(() => this.exam()?.questions ?? []);
  readonly current = computed(() => {
    const qs = this.questions();
    return qs[this.currentIndex()] ?? null;
  });
  readonly answeredCount = computed(() =>
    Object.values(this.answers()).filter((a) => a?.trim()).length,
  );
  readonly isLowTime = computed(() => this.timeLeft() <= 300);

  constructor() {
    effect(() => {
      const level = this.route.snapshot.paramMap.get('level') ?? '';
      this.level.set(level);
      if (!level) return;
      this.startExam(level);
    });

    effect(() => {
      const session = this.exam();
      if (!session || this.submitting()) return;
      this.startTimer();
    });
  }

  ngOnDestroy(): void {
    this.stopTimer();
  }

  private async startExam(level: string): Promise<void> {
    this.submitted = false;
    this.exam.set(null);
    this.answers.set({});
    this.currentIndex.set(0);
    this.confirmSubmit.set(false);
    this.loading.set(true);
    this.error.set('');

    try {
      const data = await this.api.startMockExam(level);
      const session = parseMockExamSession(data);
      this.exam.set(session);
      this.timeLeft.set(session.durationMinutes * 60);
    } catch {
      this.error.set('Không tạo được đề thi. Hãy thử lại sau.');
    } finally {
      this.loading.set(false);
    }
  }

  private startTimer(): void {
    this.stopTimer();
    this.timerId = setInterval(() => {
      this.timeLeft.update((prev) => {
        if (prev <= 1) {
          this.stopTimer();
          void this.doSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
  }

  private stopTimer(): void {
    if (this.timerId) {
      clearInterval(this.timerId);
      this.timerId = null;
    }
  }

  setAnswer(questionId: string, value: string): void {
    this.answers.update((prev) => ({ ...prev, [questionId]: value }));
  }

  playAudio(text: string): void {
    playJapanese(text);
  }

  typeLabel(q: MockExamQuestion | null): string {
    if (!q) return '';
    if (q.type === 'listening') return 'Nghe';
    if (q.type === 'multiple_choice') return 'Trắc nghiệm';
    return 'Điền từ';
  }

  formatTime(seconds: number): string {
    return formatTimer(seconds);
  }

  isAnswered(questionId: string): boolean {
    return !!this.answers()[questionId]?.trim();
  }

  getAnswer(questionId: string): string {
    return this.answers()[questionId] ?? '';
  }

  goToQuestion(index: number): void {
    this.currentIndex.set(index);
  }

  prevQuestion(): void {
    this.currentIndex.update((i) => Math.max(0, i - 1));
  }

  nextQuestion(): void {
    this.currentIndex.update((i) => Math.min(this.questions().length - 1, i + 1));
  }

  async doSubmit(): Promise<void> {
    const session = this.exam();
    if (!session || this.submitting() || this.submitted) return;
    this.submitted = true;
    this.submitting.set(true);
    this.stopTimer();

    try {
      const data = await this.api.submitMockExam(session.examId, this.answers());
      const result = parseMockExamResult(data);
      saveMockExamResult(result);
      await this.router.navigate(['/mock-exam', this.level(), 'answers']);
    } catch {
      this.error.set('Nộp bài thất bại. Phiên thi có thể đã hết hạn — hãy làm đề mới.');
      this.submitted = false;
    } finally {
      this.submitting.set(false);
    }
  }
}

@if (loading()) {
  <section class="container mock-exam-page">
    <div class="empty-state glass-panel">
      <p>Đang tạo đề thi {{ level().toUpperCase() }}...</p>
    </div>
  </section>
} @else if (error() || !exam() || !current()) {
  <section class="container mock-exam-page">
    <div class="empty-state glass-panel">
      <p>{{ error() || 'Không có câu hỏi trong đề thi.' }}</p>
      <a routerLink="/mock-exam" class="btn btn-primary">Quay lại</a>
    </div>
  </section>
} @else {
  <section class="container mock-exam-page mock-exam-take">
    <div class="mock-exam-toolbar glass-panel">
      <div>
        <h3>{{ exam()!.title }}</h3>
        <p class="toolbar-meta">Đã làm {{ answeredCount() }}/{{ questions().length }} câu</p>
      </div>
      <div class="mock-exam-timer" [class.urgent]="isLowTime()">
        ⏱ {{ formatTime(timeLeft()) }}
      </div>
    </div>

    <div class="mock-exam-layout">
      <aside class="mock-exam-palette glass-panel">
        <p class="palette-title">Danh sách câu</p>
        @for (sec of exam()!.sections; track sec.id) {
          <div class="palette-section">
            <span class="palette-section-name">{{ sec.name }}</span>
            <div class="palette-grid">
              @for (q of questions(); track q.id; let idx = $index) {
                @if (q.sectionId === sec.id) {
                  <button
                    type="button"
                    class="palette-btn"
                    [class.active]="currentIndex() === idx"
                    [class.answered]="isAnswered(q.id)"
                    (click)="goToQuestion(idx)"
                  >
                    {{ idx + 1 }}
                  </button>
                }
              }
            </div>
          </div>
        }
      </aside>

      <div class="mock-exam-main">
        <div class="question-card glass-panel">
          <div class="question-head">
            <span class="type-badge">{{ current()!.sectionName }} · Câu {{ currentIndex() + 1 }}</span>
            <span class="type-label">{{ typeLabel(current()) }}</span>
          </div>

          @if (current()!.type === 'listening' && current()!.audioText) {
            <button type="button" class="btn btn-outline" (click)="playAudio(current()!.audioText!)">
              🔊 Nghe câu hỏi
            </button>
          }

          <h3 class="question-text">{{ current()!.question }}</h3>

          @if (current()!.type === 'multiple_choice' || current()!.type === 'listening') {
            <div class="quiz-options">
              @for (option of current()!.options ?? []; track option) {
                <button
                  type="button"
                  class="quiz-option"
                  [class.selected]="answers()[current()!.id] === option"
                  (click)="setAnswer(current()!.id, option)"
                >
                  {{ option }}
                </button>
              }
            </div>
          } @else {
            <input
              type="text"
              class="fill-input"
              placeholder="Nhập đáp án..."
              [value]="getAnswer(current()!.id)"
              (input)="setAnswer(current()!.id, $any($event.target).value)"
            />
          }

          <div class="mock-exam-nav">
            <button
              type="button"
              class="btn btn-outline"
              [disabled]="currentIndex() === 0"
              (click)="prevQuestion()"
            >
              ← Câu trước
            </button>
            <button
              type="button"
              class="btn btn-outline"
              [disabled]="currentIndex() >= questions().length - 1"
              (click)="nextQuestion()"
            >
              Câu sau →
            </button>
          </div>
        </div>

        <div class="submit-bar glass-panel">
          @if (!confirmSubmit()) {
            <button type="button" class="btn btn-primary" (click)="confirmSubmit.set(true)" [disabled]="submitting()">
              Nộp bài
            </button>
          } @else {
            <div class="submit-confirm">
              <p>Bạn đã làm {{ answeredCount() }}/{{ questions().length }} câu. Nộp bài ngay?</p>
              <div class="submit-confirm-actions">
                <button type="button" class="btn btn-outline" (click)="confirmSubmit.set(false)" [disabled]="submitting()">
                  Tiếp tục làm
                </button>
                <button type="button" class="btn btn-primary" (click)="doSubmit()" [disabled]="submitting()">
                  {{ submitting() ? 'Đang nộp...' : 'Xác nhận nộp' }}
                </button>
              </div>
            </div>
          }
        </div>
      </div>
    </div>
  </section>
}

// apps/nihongo-web/src/views/MockExamTakePage.tsx
'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useMutation } from '@tanstack/react-query';
import { startMockExam, submitMockExam } from '../api';
import {
  formatTimer,
  saveMockExamResult,
  type MockExamQuestion,
  type MockExamSession,
} from '../utils/mockExam';
import ListeningPlayer from '../components/ListeningPlayer';
import './MockExam.css';
import './QuizView.css';

export default function MockExamTakePage() {
  const params = useParams();
  const level = String(params?.level ?? '');
  const router = useRouter();

  const [exam, setExam] = useState<MockExamSession | null>(null);
  const [error, setError] = useState('');
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [timeLeft, setTimeLeft] = useState(0);
  const [confirmSubmit, setConfirmSubmit] = useState(false);

  const answersRef = useRef(answers);
  answersRef.current = answers;
  const submittedRef = useRef(false);

  const startMutation = useMutation({
    mutationFn: () => startMockExam(level),
    onSuccess: (data) => {
      const session = data as unknown as MockExamSession;
      setExam(session);
      setTimeLeft(session.durationMinutes * 60);
      setError('');
    },
    onError: () => {
      setError('Không tạo được đề thi. Hãy thử lại sau.');
    },
  });

  const submitMutation = useMutation({
    mutationFn: (payload: { examId: string; answers: Record<string, string> }) =>
      submitMockExam(payload.examId, payload.answers),
    onSuccess: (result) => {
      saveMockExamResult(result as unknown as Parameters<typeof saveMockExamResult>[0]);
      router.replace(`/mock-exam/${level}/answers`);
    },
    onError: () => {
      setError('Nộp bài thất bại. Phiên thi có thể đã hết hạn — hãy làm đề mới.');
      submittedRef.current = false;
    },
  });

  const submitting = submitMutation.isPending;
  const loading = startMutation.isPending && !exam;

  const doSubmit = useCallback(async () => {
    if (!exam || submitting || submittedRef.current) return;
    submittedRef.current = true;
    submitMutation.mutate({ examId: exam.examId, answers: answersRef.current });
  }, [exam, submitting, submitMutation]);

  useEffect(() => {
    if (!level) return;
    submittedRef.current = false;
    setExam(null);
    setAnswers({});
    setCurrentIndex(0);
    setConfirmSubmit(false);
    startMutation.mutate();
  }, [level]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!exam || submitting) return undefined;

    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          void doSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [exam, submitting, doSubmit]);

  const questions: MockExamQuestion[] = exam?.questions ?? [];
  const current = questions[currentIndex];
  const answeredCount = useMemo(
    () => Object.values(answers).filter((a) => a?.trim()).length,
    [answers],
  );

  const setAnswer = (questionId: string, value: string) => {
    setAnswers((prev) => ({ ...prev, [questionId]: value }));
  };

  if (loading) {
    return (
      <div className="container mock-exam-page">
        <div className="empty-state glass-panel">
          <p>Đang tạo đề thi {level?.toUpperCase()}...</p>
        </div>
      </div>
    );
  }

  if (error || !exam || !current) {
    return (
      <div className="container mock-exam-page">
        <div className="empty-state glass-panel">
          <p>{error || 'Không có câu hỏi trong đề thi.'}</p>
          <Link href="/mock-exam" className="btn btn-primary">Quay lại</Link>
        </div>
      </div>
    );
  }

  const isLowTime = timeLeft <= 300;

  return (
    <div className="container mock-exam-page mock-exam-take">
      <div className="mock-exam-toolbar glass-panel">
        <div>
          <h3 className="mock-exam-toolbar-title">{exam.title}</h3>
          <p className="mock-exam-toolbar-meta">
            Đã làm {answeredCount}/{questions.length} câu
          </p>
        </div>
        <div className={`mock-exam-timer ${isLowTime ? 'urgent' : ''}`}>
          ⏱ {formatTimer(timeLeft)}
        </div>
      </div>

      <div className="mock-exam-layout">
        <aside className="mock-exam-palette glass-panel">
          <p className="palette-title">Danh sách câu</p>
          {exam.sections.map((sec) => (
            <div key={sec.id} className="palette-section">
              <span className="palette-section-name">{sec.name}</span>
              <div className="palette-grid">
                {questions
                  .map((q, idx) => ({ ...q, idx }))
                  .filter((q) => q.sectionId === sec.id)
                  .map((q) => (
                    <button
                      key={q.id}
                      type="button"
                      className={`palette-btn ${
                        currentIndex === q.idx ? 'active' : ''
                      } ${answers[q.id]?.trim() ? 'answered' : ''}`}
                      onClick={() => setCurrentIndex(q.idx)}
                    >
                      {q.idx + 1}
                    </button>
                  ))}
              </div>
            </div>
          ))}
        </aside>

        <div className="mock-exam-main">
          <div className="quiz-card glass-panel mock-exam-question-card">
            <div className="mock-exam-question-head">
              <span className="quiz-type-badge">
                {current.sectionName} · Câu {currentIndex + 1}
              </span>
              <span className="mock-exam-type-label">
                {current.type === 'listening'
                  ? 'Nghe'
                  : current.type === 'multiple_choice'
                    ? 'Trắc nghiệm'
                    : 'Điền từ'}
              </span>
            </div>

            {current.type === 'listening' && current.audioText && (
              <ListeningPlayer audioText={current.audioText} />
            )}

            <h3 className="quiz-question">{current.question}</h3>

            {current.type === 'multiple_choice' || current.type === 'listening' ? (
              <div className="quiz-options">
                {(current.options ?? []).map((option) => (
                  <button
                    key={option}
                    type="button"
                    className={`quiz-option ${
                      answers[current.id] === option ? 'selected' : ''
                    }`}
                    onClick={() => setAnswer(current.id, option)}
                  >
                    {option}
                  </button>
                ))}
              </div>
            ) : (
              <div className="quiz-fill">
                <input
                  type="text"
                  className="fill-input"
                  placeholder="Nhập đáp án..."
                  value={answers[current.id] ?? ''}
                  onChange={(e) => setAnswer(current.id, e.target.value)}
                />
              </div>
            )}

            <div className="mock-exam-nav">
              <button
                type="button"
                className="btn btn-outline"
                disabled={currentIndex === 0}
                onClick={() => setCurrentIndex((i) => i - 1)}
              >
                ← Câu trước
              </button>
              <button
                type="button"
                className="btn btn-outline"
                disabled={currentIndex >= questions.length - 1}
                onClick={() => setCurrentIndex((i) => i + 1)}
              >
                Câu sau →
              </button>
            </div>
          </div>

          <div className="mock-exam-submit-bar glass-panel">
            {!confirmSubmit ? (
              <button
                type="button"
                className="btn btn-primary"
                onClick={() => setConfirmSubmit(true)}
                disabled={submitting}
              >
                Nộp bài
              </button>
            ) : (
              <div className="submit-confirm">
                <p>
                  Bạn đã làm {answeredCount}/{questions.length} câu. Nộp bài ngay?
                </p>
                <div className="submit-confirm-actions">
                  <button
                    type="button"
                    className="btn btn-outline"
                    onClick={() => setConfirmSubmit(false)}
                    disabled={submitting}
                  >
                    Tiếp tục làm
                  </button>
                  <button
                    type="button"
                    className="btn btn-primary"
                    onClick={() => void doSubmit()}
                    disabled={submitting}
                  >
                    {submitting ? 'Đang nộp...' : 'Xác nhận nộp'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
