// apps/nihongo-angular/src/app/shared/page-banner-control/page-banner-control.component.ts
import { Component, inject, signal } from '@angular/core';
import { AuthService } from '../../core/services/auth.service';
import { PageBannerService } from '../../core/services/page-banner.service';
import { readBannerImageFile, type BannerScope } from '../../core/utils/page-banner.util';

@Component({
  selector: 'app-page-banner-control',
  standalone: true,
  templateUrl: './page-banner-control.component.html',
  styleUrl: './page-banner-control.component.scss',
})
export class PageBannerControlComponent {
  readonly banners = inject(PageBannerService);
  readonly auth = inject(AuthService);

  readonly open = signal(false);
  readonly scope = signal<BannerScope>('page');
  readonly preview = signal<string | null>(null);
  readonly error = signal('');
  readonly busy = signal(false);

  toggle(): void {
    this.open.update((v) => !v);
  }

  close(): void {
    this.open.set(false);
  }

  async onFileSelected(event: Event): Promise<void> {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    input.value = '';
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      this.error.set('Vui lòng chọn file ảnh (JPG, PNG, WebP…).');
      return;
    }

    this.busy.set(true);
    this.error.set('');
    try {
      this.preview.set(await readBannerImageFile(file));
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : 'Không xử lý được ảnh.');
    } finally {
      this.busy.set(false);
    }
  }

  setScope(scope: BannerScope): void {
    this.scope.set(scope);
  }

  async apply(): Promise<void> {
    const image = this.preview();
    if (!image) {
      this.error.set('Hãy chọn ảnh trước khi áp dụng.');
      return;
    }
    this.busy.set(true);
    this.error.set('');
    try {
      await this.banners.apply(image, this.scope());
      this.preview.set(null);
      this.close();
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : 'Không lưu được banner.');
    } finally {
      this.busy.set(false);
    }
  }

  async clearCurrent(): Promise<void> {
    this.busy.set(true);
    this.error.set('');
    try {
      await this.banners.remove(this.scope() === 'global' ? 'global' : 'page');
      this.preview.set(null);
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : 'Không xóa được banner.');
    } finally {
      this.busy.set(false);
    }
  }

  async clearAll(): Promise<void> {
    this.busy.set(true);
    this.error.set('');
    try {
      await this.banners.remove('all');
      this.preview.set(null);
      this.close();
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : 'Không xóa được banner.');
    } finally {
      this.busy.set(false);
    }
  }
}

@if (auth.isAdmin()) {
  <div class="page-banner-control">
    <button
      type="button"
      class="page-banner-control__toggle"
      (click)="toggle()"
      [attr.aria-expanded]="open()"
      aria-label="Đổi ảnh nền trang"
      title="Đổi ảnh nền (admin)"
    >
      🖼️
    </button>

    @if (open()) {
      <div class="page-banner-control__panel glass-panel" role="dialog" aria-label="Cài đặt ảnh nền">
        <div class="page-banner-control__header">
          <h3>Ảnh nền trang</h3>
          <button type="button" class="btn-ghost" (click)="close()" aria-label="Đóng">✕</button>
        </div>

        <p class="page-banner-control__path">
          Trang hiện tại: <code>{{ banners.currentPath() }}</code>
        </p>

        <div
          class="page-banner-control__preview"
          [style.background-image]="(preview() || banners.bannerUrl()) ? 'url(' + (preview() || banners.bannerUrl()) + ')' : null"
        >
          @if (!preview() && !banners.bannerUrl()) {
            <span>Chưa có ảnh nền</span>
          }
        </div>

        <label class="page-banner-control__upload btn-outline">
          {{ busy() ? 'Đang xử lý…' : 'Chọn ảnh từ máy' }}
          <input type="file" accept="image/*" hidden [disabled]="busy()" (change)="onFileSelected($event)" />
        </label>

        <fieldset class="page-banner-control__scope">
          <legend>Áp dụng cho</legend>
          <label>
            <input
              type="radio"
              name="banner-scope"
              [checked]="scope() === 'global'"
              (change)="setScope('global')"
            />
            <span>Tất cả các trang</span>
          </label>
          <label>
            <input
              type="radio"
              name="banner-scope"
              [checked]="scope() === 'page'"
              (change)="setScope('page')"
            />
            <span>Chỉ trang này</span>
          </label>
        </fieldset>

        @if (error()) {
          <p class="page-banner-control__error">{{ error() }}</p>
        }

        <div class="page-banner-control__actions">
          <button type="button" class="btn-primary" (click)="apply()" [disabled]="busy() || !preview()">
            Áp dụng
          </button>
          <button type="button" class="btn-outline" (click)="clearCurrent()" [disabled]="busy()">
            Xóa {{ scope() === 'global' ? 'nền chung' : 'nền trang này' }}
          </button>
          <button type="button" class="btn-ghost" (click)="clearAll()" [disabled]="busy()">Xóa tất cả</button>
        </div>
      </div>
    }
  </div>
}

// apps/nihongo-web/src/components/PageBannerControl.tsx
'use client';

import { useState } from 'react';
import { readBannerImageFile, type BannerScope } from '../utils/pageBanner';
import { usePageBanner } from '../hooks/usePageBanner';
import './PageBannerControl.css';

export default function PageBannerControl() {
  const { bannerUrl, setBanner, removeBanner, pathname, isAdmin } = usePageBanner();
  const [open, setOpen] = useState(false);
  const [scope, setScope] = useState<BannerScope>('page');
  const [preview, setPreview] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  if (!isAdmin) return null;

  const onPickFile = async (file: File | null) => {
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      setError('Vui lòng chọn file ảnh (JPG, PNG, WebP…).');
      return;
    }

    setBusy(true);
    setError('');
    try {
      const dataUrl = await readBannerImageFile(file);
      setPreview(dataUrl);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Không xử lý được ảnh.');
    } finally {
      setBusy(false);
    }
  };

  const onApply = async () => {
    if (!preview) {
      setError('Hãy chọn ảnh trước khi áp dụng.');
      return;
    }
    setBusy(true);
    setError('');
    try {
      await setBanner(preview, scope);
      setPreview(null);
      setOpen(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Không lưu được banner.');
    } finally {
      setBusy(false);
    }
  };

  const onClear = async () => {
    setBusy(true);
    setError('');
    try {
      await removeBanner(scope === 'global' ? 'global' : 'page');
      setPreview(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Không xóa được banner.');
    } finally {
      setBusy(false);
    }
  };

  const onClearAll = async () => {
    setBusy(true);
    setError('');
    try {
      await removeBanner('all');
      setPreview(null);
      setOpen(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Không xóa được banner.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="page-banner-control">
      <button
        type="button"
        className="page-banner-control__toggle"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        aria-label="Đổi ảnh nền trang"
        title="Đổi ảnh nền (admin)"
      >
        🖼️
      </button>

      {open && (
        <div className="page-banner-control__panel glass-panel" role="dialog" aria-label="Cài đặt ảnh nền">
          <div className="page-banner-control__header">
            <h3>Ảnh nền trang</h3>
            <button type="button" className="btn-ghost" onClick={() => setOpen(false)} aria-label="Đóng">
              ✕
            </button>
          </div>

          <p className="page-banner-control__path">Trang hiện tại: <code>{pathname}</code></p>

          <div
            className="page-banner-control__preview"
            style={
              (preview || bannerUrl)
                ? { backgroundImage: `url("${preview || bannerUrl}")` }
                : undefined
            }
          >
            {!preview && !bannerUrl && <span>Chưa có ảnh nền</span>}
          </div>

          <label className="page-banner-control__upload btn-outline">
            {busy ? 'Đang xử lý…' : 'Chọn ảnh từ máy'}
            <input
              type="file"
              accept="image/*"
              hidden
              disabled={busy}
              onChange={(e) => void onPickFile(e.target.files?.[0] ?? null)}
            />
          </label>

          <fieldset className="page-banner-control__scope">
            <legend>Áp dụng cho</legend>
            <label>
              <input
                type="radio"
                name="banner-scope"
                checked={scope === 'global'}
                onChange={() => setScope('global')}
              />
              <span>Tất cả các trang</span>
            </label>
            <label>
              <input
                type="radio"
                name="banner-scope"
                checked={scope === 'page'}
                onChange={() => setScope('page')}
              />
              <span>Chỉ trang này</span>
            </label>
          </fieldset>

          {error && <p className="page-banner-control__error">{error}</p>}

          <div className="page-banner-control__actions">
            <button type="button" className="btn-primary" onClick={() => void onApply()} disabled={busy || !preview}>
              Áp dụng
            </button>
            <button type="button" className="btn-outline" onClick={() => void onClear()} disabled={busy}>
              Xóa {scope === 'global' ? 'nền chung' : 'nền trang này'}
            </button>
            <button type="button" className="btn-ghost" onClick={() => void onClearAll()} disabled={busy}>
              Xóa tất cả
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
