// apps/nihongo-web/src/components/FlashcardJapaneseText.tsx
'use client';

import {
  hasOptionalBracketParts,
  parseOptionalBracketSegments,
} from '../utils/japanese';

type FlashcardJapaneseTextProps = {
  text: string;
  className?: string;
};

export default function FlashcardJapaneseText({ text, className = '' }: FlashcardJapaneseTextProps) {
  const segments = parseOptionalBracketSegments(text);
  const hasOptional = hasOptionalBracketParts(text);

  return (
    <span
      className={`flashcard-jp-text${hasOptional ? ' flashcard-jp-text--optional-mix' : ''}${
        className ? ` ${className}` : ''
      }`}
    >
      {segments.map((segment, index) =>
        segment.optional ? (
          <span key={index} className="flashcard-jp-optional">
            <span className="flashcard-jp-bracket">{segment.openBracket ?? '['}</span>
            {segment.text}
            <span className="flashcard-jp-bracket">{segment.closeBracket ?? ']'}</span>
          </span>
        ) : (
          <span key={index} className="flashcard-jp-core">
            {segment.text}
          </span>
        ),
      )}
    </span>
  );
}

// apps/nihongo-angular/src/app/shared/flashcard-japanese-text/flashcard-japanese-text.component.ts
import { Component, computed, input } from '@angular/core';
import {
  hasOptionalBracketParts,
  parseOptionalBracketSegments,
} from '../../core/utils/japanese.util';

@Component({
  selector: 'app-flashcard-japanese-text',
  standalone: true,
  template: `
    <span
      [attr.class]="
        'flashcard-jp-text' +
        (hasOptional() ? ' flashcard-jp-text--optional-mix' : '') +
        (extraClass() ? ' ' + extraClass() : '')
      "
    >
      @for (segment of segments(); track $index) {
        @if (segment.optional) {
          <span class="flashcard-jp-optional">
            <span class="flashcard-jp-bracket">{{ segment.openBracket ?? '[' }}</span>
            {{ segment.text }}
            <span class="flashcard-jp-bracket">{{ segment.closeBracket ?? ']' }}</span>
          </span>
        } @else {
          <span class="flashcard-jp-core">{{ segment.text }}</span>
        }
      }
    </span>
  `,
})
export class FlashcardJapaneseTextComponent {
  readonly text = input.required<string>();
  readonly extraClass = input('', { alias: 'className' });

  readonly segments = computed(() => parseOptionalBracketSegments(this.text()));
  readonly hasOptional = computed(() => hasOptionalBracketParts(this.text()));
}
