// apps/nihongo-angular/src/app/features/admin/admin-import-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../core/services/auth.service';
import { ApiService } from '../../core/services/api.service';
import { ApiError } from '../../core/http/api-client';

@Component({
  selector: 'app-admin-import-page',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './admin-import-page.component.html',
  styleUrl: './admin-import-page.component.scss',
})
export class AdminImportPageComponent {
  private readonly auth = inject(AuthService);
  private readonly api = inject(ApiService);

  readonly loading = signal(false);
  readonly result = signal('');

  lessonNumber = 1;
  text = '';

  async submit(): Promise<void> {
    const token = this.auth.token();
    if (!token || !this.text.trim()) return;

    this.loading.set(true);
    this.result.set('');

    try {
      const res = await this.api.adminImportVocab(token, this.lessonNumber, this.text);
      this.result.set(
        `Đã import ${res.count} từ${res.skipped ? `, bỏ qua ${res.skipped} dòng lỗi` : ''}.`,
      );
    } catch (err) {
      this.result.set(err instanceof ApiError ? err.message : 'Import thất bại');
    } finally {
      this.loading.set(false);
    }
  }
}

<div class="admin-import">
  <h1>Import từ vựng</h1>
  <p class="subtitle">Dán dữ liệu tab-separated: Kanji | Kana | Romaji | Meaning</p>

  <form class="glass-panel import-form" (ngSubmit)="submit()">
    <label>
      Số bài
      <input type="number" min="1" [(ngModel)]="lessonNumber" name="lessonNumber" />
    </label>

    <label>
      Dữ liệu
      <textarea
        rows="14"
        [(ngModel)]="text"
        name="text"
        placeholder="食べる	たべる	taberu	ăn"
      ></textarea>
    </label>

    <button type="submit" class="btn btn-primary" [disabled]="loading() || !text.trim()">
      {{ loading() ? 'Đang import…' : 'Import' }}
    </button>

    @if (result()) {
      <p class="result">{{ result() }}</p>
    }
  </form>
</div>

// apps/nihongo-web/src/views/admin/AdminImportPage.tsx
'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { adminImportVocab } from '../../api';
import { useAuth } from '../../hooks/useAuth';
import './AdminPages.css';

export default function AdminImportPage() {
  const { token, logout } = useAuth();
  const [lessonNumber, setLessonNumber] = useState(1);
  const [text, setText] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!token) return;
    setLoading(true);
    setResult(null);
    try {
      const res = await adminImportVocab(token, lessonNumber, text);
      setResult(`Đã import ${res.count} từ${res.skipped ? `, bỏ qua ${res.skipped} dòng lỗi` : ''}.`);
    } catch (err) {
      setResult(err instanceof Error ? err.message : 'Import thất bại');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="admin-dashboard">
      <header className="admin-topbar glass-panel">
        <div>
          <h1>Import từ vựng</h1>
          <p>
            <Link href="/admin">← Dashboard</Link>
          </p>
        </div>
        <button
          type="button"
          className="btn btn-outline"
          onClick={() => {
            void logout();
          }}
        >
          Đăng xuất
        </button>
      </header>

      <form className="glass-panel admin-import-form" onSubmit={handleSubmit}>
        <label>
          Số bài
          <input
            type="number"
            min={1}
            value={lessonNumber}
            onChange={(e) => setLessonNumber(Number(e.target.value))}
          />
        </label>
        <label>
          Dữ liệu (tab-separated: Kanji | Kana | Romaji | Meaning)
          <textarea
            rows={12}
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={'食べる\tたべる\ttaberu\tăn'}
          />
        </label>
        <button type="submit" className="btn btn-primary" disabled={loading || !text.trim()}>
          {loading ? 'Đang import...' : 'Import'}
        </button>
        {result && <p className="admin-meta">{result}</p>}
      </form>
    </div>
  );
}
