// apps/nihongo-web/src/views/admin/AdminLoginPage.tsx
'use client';

import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { ApiError } from '@/types/api';
import './AdminPages.css';

export default function AdminLoginPage() {
  const { loginAdmin, isAuthenticated, isAdmin, logout } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const [email, setEmail] = useState('admin@nihongo.local');
  const [password, setPassword] = useState('admin123');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (searchParams?.get('reason') === 'forbidden') {
      setError('Tài khoản hiện tại không có quyền admin. Đăng nhập bằng tài khoản admin.');
    }
  }, [searchParams]);

  useEffect(() => {
    if (isAuthenticated && isAdmin) {
      router.replace('/admin');
    }
  }, [isAuthenticated, isAdmin, router]);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      if (isAuthenticated && !isAdmin) {
        await logout();
      }
      await loginAdmin(email, password);
      router.replace('/admin');
    } catch (err) {
      setError(err instanceof ApiError ? err.message : err instanceof Error ? err.message : 'Đăng nhập thất bại');
    } finally {
      setLoading(false);
    }
  };
  if (isAuthenticated && isAdmin) {
    return (
      <div className="admin-login-page">
        <div className="empty-state glass-panel">
          <p>Đang chuyển hướng...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="admin-login-page">
      <form className="admin-login-card glass-panel" onSubmit={handleSubmit}>
        <h1>Admin Login</h1>
        <p className="admin-login-sub">JWT auth — dùng Swagger để test API</p>

        {error && <p className="admin-error">{error}</p>}

        <label>
          Email
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </label>
        <label>
          Mật khẩu
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </label>

        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading ? 'Đang đăng nhập...' : 'Đăng nhập'}
        </button>

        <p className="admin-login-links">
          <Link href="/">← Về app học</Link>
          <a href="/api/docs" target="_blank" rel="noreferrer">
            Swagger ↗
          </a>
        </p>
      </form>
    </div>
  );
}

// apps/nihongo-angular/src/app/features/admin/admin-login-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiError } from '../../core/http/api-client';

@Component({
  selector: 'app-admin-login-page',
  standalone: true,
  imports: [FormsModule, RouterLink],
  templateUrl: './admin-login-page.component.html',
  styleUrl: './admin-login-page.component.scss',
})
export class AdminLoginPageComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);

  readonly loading = signal(false);
  readonly error = signal('');

  email = '';
  password = '';

  private get redirectUrl(): string {
    return this.route.snapshot.queryParamMap.get('redirect') ?? '/admin';
  }

  async submit(): Promise<void> {
    if (!this.email.trim() || !this.password) {
      this.error.set('Nhập email và mật khẩu admin.');
      return;
    }

    this.loading.set(true);
    this.error.set('');

    try {
      await this.auth.loginAdmin(this.email.trim(), this.password);
      await this.router.navigateByUrl(this.redirectUrl);
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Đăng nhập thất bại');
    } finally {
      this.loading.set(false);
    }
  }
}

<div class="admin-login container">
  <div class="login-card glass-panel">
    <h1>Admin login</h1>
    <p class="subtitle">Chỉ tài khoản có quyền ADMIN.</p>

    @if (error()) {
      <p class="error">{{ error() }}</p>
    }

    <form (ngSubmit)="submit()">
      <label>
        Email
        <input type="email" [(ngModel)]="email" name="email" autocomplete="username" required />
      </label>
      <label>
        Mật khẩu
        <input type="password" [(ngModel)]="password" name="password" autocomplete="current-password" required />
      </label>
      <button type="submit" class="btn btn-primary" [disabled]="loading()">
        {{ loading() ? 'Đang đăng nhập…' : 'Đăng nhập' }}
      </button>
    </form>

    <a routerLink="/" class="footer-link">← Về app học</a>
  </div>
</div>
