// apps/nihongo-web/src/components/LessonSelector.tsx
'use client';

import { useMemo } from 'react';
import { useLessonsQuery } from '../hooks/queries';

export type LessonCountKind = 'vocab' | 'grammar' | 'none';

interface LessonSelectorProps {
  value: number;
  onChange: (lessonNumber: number) => void;
  id?: string;
  filterWithContent?: boolean;
  /** Loại số lượng hiển thị cạnh tên bài trong dropdown */
  countKind?: LessonCountKind;
  /** @deprecated Dùng countKind="vocab" | "none" */
  showVocabCount?: boolean;
}

function countSuffixForLesson(
  lesson: { _count?: { vocabularies?: number; grammars?: number } },
  countKind: LessonCountKind,
): string {
  if (countKind === 'none') return '';

  const count =
    countKind === 'grammar'
      ? lesson._count?.grammars
      : lesson._count?.vocabularies;

  if (count == null) return '';

  return countKind === 'grammar' ? ` (${count} mục)` : ` (${count} từ)`;
}

export default function LessonSelector({
  value,
  onChange,
  id = 'lesson-select',
  filterWithContent = true,
  countKind,
  showVocabCount = true,
}: LessonSelectorProps) {
  const resolvedCountKind: LessonCountKind =
    countKind ?? (showVocabCount ? 'vocab' : 'none');
  const { data, isLoading, isError } = useLessonsQuery();

  const lessons = useMemo(() => {
    if (!data) return [];
    if (!filterWithContent) return data;
    return data.filter(
      (l) =>
        (l._count?.vocabularies ?? 0) > 0 ||
        (l._count?.grammars ?? 0) > 0 ||
        (l._count?.exercises ?? 0) > 0,
    );
  }, [data, filterWithContent]);

  if (isLoading) {
    return (
      <div className="lesson-selector">
        <label>Chọn bài học: </label>
        <span className="select-loading">Đang tải...</span>
      </div>
    );
  }

  if (isError || lessons.length === 0) {
    return (
      <div className="lesson-selector">
        <label>Chọn bài học: </label>
        <span className="select-loading">Chưa có dữ liệu</span>
      </div>
    );
  }

  return (
    <div className="lesson-selector">
      <label htmlFor={id}>Chọn bài học: </label>
      <select
        id={id}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="select-input"
      >
        {lessons.map((lesson) => (
          <option key={lesson.lessonNumber} value={lesson.lessonNumber}>
            Bài {lesson.lessonNumber}
            {countSuffixForLesson(lesson, resolvedCountKind)}
          </option>
        ))}
      </select>
    </div>
  );
}

// apps/nihongo-angular/src/app/shared/lesson-selector/lesson-selector.component.ts
import { Component, Input, output } from '@angular/core';
import type { Lesson } from '../../core/models/api.models';

export type LessonCountKind = 'vocab' | 'grammar' | 'none';

@Component({
  selector: 'app-lesson-selector',
  standalone: true,
  templateUrl: './lesson-selector.component.html',
  styleUrl: './lesson-selector.component.scss',
})
export class LessonSelectorComponent {
  @Input({ required: true }) lessons: Lesson[] = [];
  @Input({ required: true }) value = 1;
  @Input() filterWithContent = true;
  @Input() countKind: LessonCountKind = 'vocab';
  readonly valueChange = output<number>();

  get visibleLessons(): Lesson[] {
    if (!this.filterWithContent) return this.lessons;
    return this.lessons.filter((lesson) => this.hasContent(lesson));
  }

  onSelect(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.valueChange.emit(Number(target.value));
  }

  countSuffix(lesson: Lesson): string {
    if (this.countKind === 'none') return '';

    const count =
      this.countKind === 'grammar'
        ? lesson._count?.grammars
        : lesson._count?.vocabularies;

    if (count == null) return '';

    return this.countKind === 'grammar' ? ` (${count} mục)` : ` (${count} từ)`;
  }

  labelFor(lesson: Lesson): string {
    return lesson.title ?? `Bài ${lesson.lessonNumber}`;
  }

  private hasContent(lesson: Lesson): boolean {
    if (this.countKind === 'grammar') {
      return (lesson._count?.grammars ?? 0) > 0;
    }
    if (this.countKind === 'vocab') {
      return (lesson._count?.vocabularies ?? 0) > 0;
    }
    return (
      (lesson._count?.vocabularies ?? 0) > 0 ||
      (lesson._count?.grammars ?? 0) > 0 ||
      (lesson._count?.exercises ?? 0) > 0
    );
  }
}

<div class="lesson-selector">
  <label for="lesson-select">Chọn bài học:</label>
  <select id="lesson-select" class="select-input" [value]="value" (change)="onSelect($event)">
    @for (lesson of visibleLessons; track lesson.lessonNumber) {
      <option [value]="lesson.lessonNumber">
        {{ labelFor(lesson) }}{{ countSuffix(lesson) }}
      </option>
    }
  </select>
</div>
