// apps/nihongo-web/src/views/auth/ProfilePage.tsx
'use client';

import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import PaymentMethodsSection from '@/components/PaymentMethodsSection';
import { ApiError } from '@/types/api';
import './AuthPages.css';

const JLPT_LEVELS = ['', 'N5', 'N4', 'N3', 'N2', 'N1'] as const;

export default function ProfilePage() {
  const { user, token, isAuthenticated, updateProfile, logout } = useAuth();
  const router = useRouter();

  const [name, setName] = useState('');
  const [avatarUrl, setAvatarUrl] = useState('');
  const [nativeLanguage, setNativeLanguage] = useState('vi');
  const [targetJlptLevel, setTargetJlptLevel] = useState('');
  const [studyGoalMinutes, setStudyGoalMinutes] = useState(30);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isAuthenticated) {
      router.replace('/login?redirect=/profile');
    }
  }, [isAuthenticated, router]);

  useEffect(() => {
    if (!user) return;
    setName(user.name ?? '');
    setAvatarUrl(user.avatarUrl ?? '');
    setNativeLanguage(user.nativeLanguage ?? 'vi');
    setTargetJlptLevel(user.targetJlptLevel ?? '');
    setStudyGoalMinutes(user.studyGoalMinutes ?? 30);
  }, [user]);

  if (!user) {
    return (
      <div className="profile-page">
        <div className="empty-state glass-panel">Đang tải hồ sơ...</div>
      </div>
    );
  }

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);
    try {
      await updateProfile({
        name: name.trim() || undefined,
        avatarUrl: avatarUrl.trim() || null,
        nativeLanguage,
        targetJlptLevel: targetJlptLevel || null,
        studyGoalMinutes,
      });
      setSuccess('Đã cập nhật thông tin');
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Cập nhật thất bại');
    } finally {
      setLoading(false);
    }
  };

  const initials = (user.name ?? user.email).slice(0, 1).toUpperCase();

  return (
    <div className="profile-page">
      <div className="profile-card glass-panel">
        <h1>Hồ sơ của bạn</h1>
        <p className="profile-meta">{user.email}</p>

        <div className="profile-badges">
          {user.isGoogleLinked && <span className="profile-badge">Google đã liên kết</span>}
          {user.hasPassword && <span className="profile-badge">Email + mật khẩu</span>}
          {user.role === 'ADMIN' && <span className="profile-badge">Admin</span>}
        </div>

        <div className="auth-user-chip" style={{ maxWidth: 'none' }}>
          {user.avatarUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={user.avatarUrl} alt="" className="auth-avatar" />
          ) : (
            <span className="auth-avatar">{initials}</span>
          )}
          <span className="auth-user-name">{user.name ?? user.email}</span>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <p className="auth-error">{error}</p>}
          {success && <p className="auth-success">{success}</p>}

          <div className="auth-field">
            <label>
              Tên hiển thị
              <input value={name} onChange={(e) => setName(e.target.value)} maxLength={120} />
            </label>
          </div>

          <div className="auth-field">
            <label>
              Ảnh đại diện (URL)
              <input
                type="url"
                value={avatarUrl}
                onChange={(e) => setAvatarUrl(e.target.value)}
                placeholder="https://..."
              />
            </label>
          </div>

          <div className="auth-field">
            <label>
              Ngôn ngữ mẹ đẻ
              <select value={nativeLanguage} onChange={(e) => setNativeLanguage(e.target.value)}>
                <option value="vi">Tiếng Việt</option>
                <option value="en">English</option>
                <option value="ja">日本語</option>
              </select>
            </label>
          </div>

          <div className="auth-field">
            <label>
              Mục tiêu JLPT
              <select
                value={targetJlptLevel}
                onChange={(e) => setTargetJlptLevel(e.target.value)}
              >
                {JLPT_LEVELS.map((lv) => (
                  <option key={lv || 'none'} value={lv}>
                    {lv || 'Chưa chọn'}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <div className="auth-field">
            <label>
              Mục tiêu học mỗi ngày (phút)
              <input
                type="number"
                min={5}
                max={480}
                value={studyGoalMinutes}
                onChange={(e) => setStudyGoalMinutes(Number(e.target.value))}
              />
            </label>
          </div>

          <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
            {loading ? 'Đang lưu...' : 'Lưu thay đổi'}
          </button>
        </form>

        <div className="profile-actions">
          <Link href="/payments" className="btn btn-outline">
            Lịch sử thanh toán
          </Link>
          <Link href="/" className="btn btn-outline">
            Về trang chủ
          </Link>
          <button
            type="button"
            className="btn btn-outline"
            onClick={() => {
              void logout().then(() => router.push('/'));
            }}
          >
            Đăng xuất
          </button>
        </div>
      </div>

      {token && <PaymentMethodsSection token={token} />}
    </div>
  );
}

// apps/nihongo-angular/src/app/features/auth/profile-page.component.ts
import { Component, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiError } from '../../core/http/api-client';
import type { UpdateProfileInput } from '../../core/models/api.models';
import { PaymentMethodsComponent } from '../../shared/payment-methods/payment-methods.component';

const JLPT_LEVELS = ['', 'N5', 'N4', 'N3', 'N2', 'N1'] as const;

@Component({
  selector: 'app-profile-page',
  standalone: true,
  imports: [FormsModule, RouterLink, PaymentMethodsComponent],
  templateUrl: './profile-page.component.html',
})
export class ProfilePageComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly user = this.auth.user;
  readonly token = this.auth.token;
  readonly jlptLevels = JLPT_LEVELS;
  readonly loading = signal(false);
  readonly success = signal('');
  readonly error = signal('');

  name = '';
  avatarUrl = '';
  nativeLanguage = 'vi';
  targetJlptLevel = '';
  studyGoalMinutes = 30;

  constructor() {
    effect(() => {
      const u = this.auth.user();
      if (!u) return;
      this.name = u.name ?? '';
      this.avatarUrl = u.avatarUrl ?? '';
      this.nativeLanguage = u.nativeLanguage ?? 'vi';
      this.targetJlptLevel = u.targetJlptLevel ?? '';
      this.studyGoalMinutes = u.studyGoalMinutes ?? 30;
    });

    if (!this.auth.isAuthenticated()) {
      void this.router.navigate(['/login'], { queryParams: { redirect: '/profile' } });
    }
  }

  label(): string {
    const u = this.user();
    if (!u) return '';
    return u.name?.trim() || u.email.split('@')[0];
  }

  initials(): string {
    return this.label().slice(0, 1).toUpperCase();
  }

  async submit(): Promise<void> {
    this.loading.set(true);
    this.success.set('');
    this.error.set('');

    const data: UpdateProfileInput = {
      name: this.name.trim() || undefined,
      avatarUrl: this.avatarUrl.trim() || null,
      nativeLanguage: this.nativeLanguage,
      targetJlptLevel: this.targetJlptLevel || null,
      studyGoalMinutes: this.studyGoalMinutes,
    };

    try {
      await this.auth.updateProfile(data);
      this.success.set('Đã cập nhật thông tin');
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Cập nhật thất bại');
    } finally {
      this.loading.set(false);
    }
  }

  async logout(): Promise<void> {
    await this.auth.logout();
    await this.router.navigate(['/']);
  }
}

<div class="profile-page">
  @if (user(); as u) {
    <div class="profile-card glass-panel">
      <h1>Hồ sơ của bạn</h1>
      <p class="profile-meta">{{ u.email }}</p>

      <div class="profile-badges">
        @if (u.isGoogleLinked) {
          <span class="profile-badge">Google đã liên kết</span>
        }
        @if (u.hasPassword) {
          <span class="profile-badge">Email + mật khẩu</span>
        }
        @if (u.role === 'ADMIN') {
          <span class="profile-badge">Admin</span>
        }
      </div>

      <div class="auth-user-chip" style="max-width: none">
        @if (u.avatarUrl) {
          <img [src]="u.avatarUrl" alt="" class="auth-avatar" />
        } @else {
          <span class="auth-avatar">{{ initials() }}</span>
        }
        <span class="auth-user-name">{{ label() }}</span>
      </div>

      <form (ngSubmit)="submit()" class="auth-form">
        @if (error()) {
          <p class="auth-error">{{ error() }}</p>
        }
        @if (success()) {
          <p class="auth-success">{{ success() }}</p>
        }

        <div class="auth-field">
          <label>
            Tên hiển thị
            <input type="text" [(ngModel)]="name" name="name" maxlength="120" />
          </label>
        </div>

        <div class="auth-field">
          <label>
            Ảnh đại diện (URL)
            <input
              type="url"
              [(ngModel)]="avatarUrl"
              name="avatarUrl"
              placeholder="https://..."
            />
          </label>
        </div>

        <div class="auth-field">
          <label>
            Ngôn ngữ mẹ đẻ
            <select [(ngModel)]="nativeLanguage" name="nativeLanguage">
              <option value="vi">Tiếng Việt</option>
              <option value="en">English</option>
              <option value="ja">日本語</option>
            </select>
          </label>
        </div>

        <div class="auth-field">
          <label>
            Mục tiêu JLPT
            <select [(ngModel)]="targetJlptLevel" name="targetJlptLevel">
              @for (lv of jlptLevels; track lv || 'none') {
                <option [value]="lv">{{ lv || 'Chưa chọn' }}</option>
              }
            </select>
          </label>
        </div>

        <div class="auth-field">
          <label>
            Mục tiêu học mỗi ngày (phút)
            <input
              type="number"
              min="5"
              max="480"
              [(ngModel)]="studyGoalMinutes"
              name="studyGoalMinutes"
            />
          </label>
        </div>

        <button type="submit" class="btn btn-primary btn-block" [disabled]="loading()">
          {{ loading() ? 'Đang lưu...' : 'Lưu thay đổi' }}
        </button>
      </form>

      <div class="profile-actions">
        <a routerLink="/payments" class="btn btn-outline">Lịch sử thanh toán</a>
        <a routerLink="/" class="btn btn-outline">Về trang chủ</a>
        <button type="button" class="btn btn-outline" (click)="logout()">Đăng xuất</button>
      </div>
    </div>

    @if (token(); as authToken) {
      <app-payment-methods [token]="authToken" />
    }
  } @else {
    <div class="empty-state glass-panel">Đang tải hồ sơ...</div>
  }
</div>
