// apps/nihongo-web/src/components/FuriganaText.tsx
'use client';

import { renderFuriganaParts } from '@/utils/furiganaDisplay';

export default function FuriganaText({
  text,
  show = true,
  className,
}: {
  text: string;
  show?: boolean;
  className?: string;
}) {
  if (!show) {
    return <span className={className}>{text.replace(/[（(][ぁ-んァ-ンー]+[）)]/g, '')}</span>;
  }
  const parts = renderFuriganaParts(text);
  return (
    <span className={className}>
      {parts.map((part, i) => {
        if ('text' in part) return <span key={i}>{part.text}</span>;
        return (
          <ruby key={i}>
            {part.kanji}
            <rt>{part.reading}</rt>
          </ruby>
        );
      })}
    </span>
  );
}

export function FuriganaToggle({
  on,
  onToggle,
}: {
  on: boolean;
  onToggle: () => void;
}) {
  return (
    <label className="furigana-toggle">
      <input type="checkbox" checked={on} onChange={onToggle} />
      <span>Hiện furigana</span>
    </label>
  );
}

// apps/nihongo-angular/src/app/shared/furigana-text/furigana-text.component.ts
import { Component, Input } from '@angular/core';
import { renderFuriganaParts, stripParenFurigana } from '../../core/utils/furiganaDisplay';

type FuriPart = { kanji: string; reading?: string } | { text: string };

@Component({
  selector: 'app-furigana-text',
  standalone: true,
  template: `
    @if (!show) {
      <span>{{ stripped }}</span>
    } @else {
      @for (part of parts; track $index) {
        @if (rubyOf(part); as ruby) {
          <ruby>{{ ruby.kanji }}<rt>{{ ruby.reading }}</rt></ruby>
        } @else {
          <span>{{ textOf(part) }}</span>
        }
      }
    }
  `,
})
export class FuriganaTextComponent {
  @Input({ required: true }) text = '';
  @Input() show = true;

  get parts(): FuriPart[] {
    return renderFuriganaParts(this.text);
  }

  get stripped(): string {
    return stripParenFurigana(this.text);
  }

  rubyOf(part: FuriPart): { kanji: string; reading: string } | null {
    if ('reading' in part && part.reading) return { kanji: part.kanji, reading: part.reading };
    return null;
  }

  textOf(part: FuriPart): string {
    return 'text' in part ? part.text : part.kanji;
  }
}
