// apps/nihongo-web/src/components/EnglishAppSwitcher.tsx
'use client';

import { useQuery } from '@tanstack/react-query';

type AppFeaturesResponse = {
  english: { enabled: boolean; url: string };
};

export default function EnglishAppSwitcher() {
  const { data } = useQuery({
    queryKey: ['app-features'],
    queryFn: async () => {
      const response = await fetch('/app-features', { cache: 'no-store' });
      if (!response.ok) {
        return { english: { enabled: false, url: '' } };
      }
      return (await response.json()) as AppFeaturesResponse;
    },
    staleTime: 30_000,
  });

  if (!data?.english.enabled) {
    return null;
  }

  return (
    <a href={data.english.url} className="nav-link app-switcher">
      🇬🇧 English
    </a>
  );
}

// apps/nihongo-angular/src/app/shared/english-app-switcher/english-app-switcher.component.ts
import { Component, OnInit, signal } from '@angular/core';

interface AppFeaturesResponse {
  english: { enabled: boolean; url: string };
}

@Component({
  selector: 'app-english-app-switcher',
  standalone: true,
  template: `
    @if (englishUrl()) {
      <a [href]="englishUrl()!" class="nav-link app-switcher">🇬🇧 English</a>
    }
  `,
})
export class EnglishAppSwitcherComponent implements OnInit {
  readonly englishUrl = signal<string | null>(null);

  ngOnInit(): void {
    void this.load();
  }

  private async load(): Promise<void> {
    try {
      const res = await fetch('/app-features', { cache: 'no-store' });
      if (!res.ok) return;
      const data = (await res.json()) as AppFeaturesResponse;
      if (data.english?.enabled && data.english.url) {
        this.englishUrl.set(data.english.url);
      }
    } catch {
      /* optional feature */
    }
  }
}
