// apps/nihongo-angular/src/app/features/auth/auth-callback-page.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiError } from '../../core/http/api-client';
import { completeKeycloakLogin } from '../../core/utils/keycloak.util';

@Component({
  selector: 'app-auth-callback-page',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="auth-page">
      <div class="auth-card glass-panel">
        <h1>Keycloak</h1>
        @if (error()) {
          <p class="auth-error">{{ error() }}</p>
          <p class="auth-footer-link"><a routerLink="/login">← Quay lại đăng nhập</a></p>
        } @else {
          <p class="auth-sub">Đang hoàn tất đăng nhập...</p>
        }
      </div>
    </div>
  `,
})
export class AuthCallbackPageComponent implements OnInit {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly error = signal('');

  async ngOnInit(): Promise<void> {
    if (this.auth.isAuthenticated()) {
      await this.router.navigateByUrl('/');
      return;
    }

    try {
      const user = await completeKeycloakLogin();
      if (!user.access_token) throw new Error('Keycloak không trả access_token');
      const authUser = await this.auth.loginWithOidc(user.access_token, user.id_token);
      const redirect = sessionStorage.getItem('kc_post_login_redirect') ?? '/';
      sessionStorage.removeItem('kc_post_login_redirect');
      const dest = authUser.role === 'ADMIN' && redirect === '/' ? '/admin' : redirect;
      await this.router.navigateByUrl(dest);
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Đăng nhập Keycloak thất bại');
    }
  }
}

// apps/nihongo-web/src/views/auth/AuthCallbackPage.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { completeKeycloakLogin } from '@/lib/keycloak';
import { resolvePostAuthRedirect } from '@/lib/auth-redirect';
import { ApiError } from '@/types/api';
import '@/views/auth/AuthPages.css';

export default function AuthCallbackPage() {
  const { loginWithOidc, isAuthenticated, isAdmin } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const [error, setError] = useState('');

  useEffect(() => {
    if (isAuthenticated) {
      router.replace(resolvePostAuthRedirect(isAdmin ? 'ADMIN' : 'USER', null));
      return;
    }

    let cancelled = false;
    (async () => {
      try {
        const user = await completeKeycloakLogin();
        const accessToken = user.access_token;
        if (!accessToken) throw new Error('Keycloak không trả access_token');
        const authUser = await loginWithOidc(accessToken, user.id_token);
        if (cancelled) return;
        const redirect = sessionStorage.getItem('kc_post_login_redirect');
        sessionStorage.removeItem('kc_post_login_redirect');
        router.replace(resolvePostAuthRedirect(authUser.role, redirect));
      } catch (err) {
        if (cancelled) return;
        setError(
          err instanceof ApiError
            ? err.message
            : err instanceof Error
              ? err.message
              : 'Đăng nhập Keycloak thất bại',
        );
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [isAuthenticated, isAdmin, loginWithOidc, router, searchParams]);

  return (
    <div className="auth-page">
      <div className="auth-card glass-panel">
        <h1>Keycloak</h1>
        {error ? (
          <>
            <p className="auth-error">{error}</p>
            <p className="auth-footer-link">
              <a href="/login">← Quay lại đăng nhập</a>
            </p>
          </>
        ) : (
          <p className="auth-sub">Đang hoàn tất đăng nhập...</p>
        )}
      </div>
    </div>
  );
}
