// apps/nihongo-angular/src/app/features/auth/login-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiError } from '../../core/http/api-client';
import { GoogleSignInButtonComponent } from '../../shared/google-sign-in-button/google-sign-in-button.component';
import { isKeycloakConfigured, startKeycloakLogin } from '../../core/utils/keycloak.util';

type AuthMode = 'login' | 'register';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [FormsModule, RouterLink, GoogleSignInButtonComponent],
  templateUrl: './login-page.component.html',
})
export class LoginPageComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);

  readonly mode = signal<AuthMode>(
    this.route.snapshot.queryParamMap.get('mode') === 'register' ? 'register' : 'login',
  );
  readonly loading = signal(false);
  readonly kcLoading = signal(false);
  readonly error = signal('');
  readonly keycloakEnabled = isKeycloakConfigured();
  readonly showDevLogin = signal(!this.keycloakEnabled);

  email = '';
  password = '';

  constructor() {
    if (this.auth.isAuthenticated()) {
      void this.router.navigateByUrl(this.redirectUrl);
    }
  }

  private get redirectUrl(): string {
    return this.route.snapshot.queryParamMap.get('redirect') ?? '/';
  }

  switchMode(next: AuthMode): void {
    this.mode.set(next);
    this.error.set('');
    void this.router.navigate([], {
      relativeTo: this.route,
      queryParams: { mode: next === 'register' ? 'register' : null },
      queryParamsHandling: 'merge',
      replaceUrl: true,
    });
  }

  revealDevLogin(): void {
    this.showDevLogin.set(true);
  }

  async onKeycloak(): Promise<void> {
    this.error.set('');
    this.kcLoading.set(true);
    try {
      const redirect = this.redirectUrl;
      if (redirect && redirect !== '/') {
        sessionStorage.setItem('kc_post_login_redirect', redirect);
      } else {
        sessionStorage.removeItem('kc_post_login_redirect');
      }
      await startKeycloakLogin();
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Không mở được Keycloak');
      this.kcLoading.set(false);
    }
  }

  onGoogleSuccess(role: string): void {
    const dest = role === 'ADMIN' && this.redirectUrl === '/' ? '/admin' : this.redirectUrl;
    void this.router.navigateByUrl(dest);
  }

  onGoogleError(message: string): void {
    this.error.set(message);
  }

  async submit(): Promise<void> {
    if (!this.email.trim() || !this.password) {
      this.error.set('Vui lòng nhập email và mật khẩu.');
      return;
    }

    this.loading.set(true);
    this.error.set('');

    try {
      if (this.mode() === 'register') {
        await this.auth.register(this.email.trim(), this.password);
      } else {
        await this.auth.login(this.email.trim(), this.password);
      }
      await this.router.navigateByUrl(this.redirectUrl);
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Đăng nhập thất bại');
    } finally {
      this.loading.set(false);
    }
  }
}

<div class="auth-page">
  <div class="auth-card glass-panel">
    <h1>{{ mode() === 'register' ? 'Tạo tài khoản' : 'Đăng nhập' }}</h1>
    <p class="auth-sub">
      @if (keycloakEnabled) {
        Đăng nhập qua Keycloak (OIDC) để đồng bộ tiến độ học
      } @else if (mode() === 'register') {
        Dùng Gmail để đăng ký nhanh, hoặc email + mật khẩu bên dưới
      } @else {
        Đăng nhập bằng Gmail hoặc email để đồng bộ tiến độ học
      }
    </p>

    @if (keycloakEnabled) {
      <button
        type="button"
        class="btn btn-primary btn-block"
        [disabled]="kcLoading()"
        (click)="onKeycloak()"
      >
        {{ kcLoading() ? 'Đang chuyển tới Keycloak...' : 'Đăng nhập Keycloak' }}
      </button>
      <div class="auth-divider">hoặc</div>
    }

    <div class="auth-tabs" role="tablist" aria-label="Chọn đăng nhập hoặc đăng ký">
      <button
        type="button"
        role="tab"
        class="auth-tab"
        [class.active]="mode() === 'login'"
        [attr.aria-selected]="mode() === 'login'"
        (click)="switchMode('login')"
      >
        Đăng nhập
      </button>
      <button
        type="button"
        role="tab"
        class="auth-tab"
        [class.active]="mode() === 'register'"
        [attr.aria-selected]="mode() === 'register'"
        (click)="switchMode('register')"
      >
        Đăng ký
      </button>
    </div>

    <app-google-sign-in-button
      [mode]="mode()"
      (googleError)="onGoogleError($event)"
      (googleSuccess)="onGoogleSuccess($event)"
    />

    @if (keycloakEnabled && !showDevLogin()) {
      <button type="button" class="btn btn-ghost btn-block" style="margin-top: 0.75rem" (click)="revealDevLogin()">
        Dev login (email / mật khẩu)
      </button>
    } @else {
      <div class="auth-divider">
        @if (keycloakEnabled) {
          Dev login
        } @else {
          hoặc dùng email@if (mode() === 'register') { & mật khẩu }
        }
      </div>

      <form (ngSubmit)="submit()" class="auth-form">
        @if (error()) {
          <p class="auth-error">{{ error() }}</p>
        }

        <div class="auth-field">
          <label>
            Email
            <input
              type="email"
              [(ngModel)]="email"
              name="email"
              autocomplete="email"
              placeholder="you@example.com"
              required
            />
          </label>
        </div>

        <div class="auth-field">
          <label>
            Mật khẩu
            <input
              type="password"
              [(ngModel)]="password"
              name="password"
              [attr.autocomplete]="mode() === 'register' ? 'new-password' : 'current-password'"
              placeholder="Tối thiểu 8 ký tự"
              minlength="8"
              required
            />
          </label>
        </div>

        <button type="submit" class="btn btn-primary btn-block" [disabled]="loading()">
          {{
            loading()
              ? 'Đang xử lý...'
              : mode() === 'register'
                ? 'Tạo tài khoản'
                : 'Đăng nhập'
          }}
        </button>
      </form>
    }

    @if (error() && !showDevLogin()) {
      <p class="auth-error">{{ error() }}</p>
    }

    <p class="auth-footer-link">
      <a routerLink="/">← Về trang chủ</a>
    </p>
  </div>
</div>

// apps/nihongo-web/src/views/auth/LoginPage.tsx
'use client';

import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import GoogleSignInButton from '@/components/GoogleSignInButton';
import { useAuth } from '@/hooks/useAuth';
import { resolvePostAuthRedirect } from '@/lib/auth-redirect';
import { isKeycloakConfigured, startKeycloakLogin } from '@/lib/keycloak';
import { ApiError } from '@/types/api';
import './AuthPages.css';

type AuthMode = 'login' | 'register';

export default function LoginPage() {
  const { login, register, isAuthenticated, isAdmin } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const redirectTo = searchParams?.get('redirect') ?? null;
  const keycloakEnabled = isKeycloakConfigured();

  const [mode, setMode] = useState<AuthMode>(
    searchParams?.get('mode') === 'register' ? 'register' : 'login',
  );
  const [showDevLogin, setShowDevLogin] = useState(!keycloakEnabled);
  const [kcLoading, setKcLoading] = useState(false);

  const switchMode = (next: AuthMode) => {
    setMode(next);
    const params = new URLSearchParams(searchParams?.toString() ?? '');
    if (next === 'register') {
      params.set('mode', 'register');
    } else {
      params.delete('mode');
    }
    const qs = params.toString();
    router.replace(qs ? `/login?${qs}` : '/login', { scroll: false });
  };
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isAuthenticated) return;
    router.replace(resolvePostAuthRedirect(isAdmin ? 'ADMIN' : 'USER', redirectTo));
  }, [isAuthenticated, isAdmin, redirectTo, router]);

  useEffect(() => {
    setMode(searchParams?.get('mode') === 'register' ? 'register' : 'login');
  }, [searchParams]);

  const handleKeycloak = async () => {
    setError('');
    setKcLoading(true);
    try {
      if (redirectTo) sessionStorage.setItem('kc_post_login_redirect', redirectTo);
      else sessionStorage.removeItem('kc_post_login_redirect');
      await startKeycloakLogin();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Không mở được Keycloak');
      setKcLoading(false);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const authUser =
        mode === 'register'
          ? await register(email, password)
          : await login(email, password);
      router.push(resolvePostAuthRedirect(authUser.role, redirectTo));
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : err instanceof Error ? err.message : 'Thất bại',
      );
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleSuccess = (role: string) => {
    router.push(resolvePostAuthRedirect(role, redirectTo));
  };

  if (isAuthenticated) {
    return (
      <div className="auth-page">
        <div className="empty-state glass-panel">Đang chuyển hướng...</div>
      </div>
    );
  }

  return (
    <div className="auth-page">
      <div className="auth-card glass-panel">
        <h1>{mode === 'register' ? 'Tạo tài khoản' : 'Đăng nhập'}</h1>
        <p className="auth-sub">
          {keycloakEnabled
            ? 'Đăng nhập qua Keycloak (OIDC) để đồng bộ tiến độ học'
            : mode === 'register'
              ? 'Dùng Gmail để đăng ký nhanh, hoặc email + mật khẩu bên dưới'
              : 'Đăng nhập bằng Gmail hoặc email để đồng bộ tiến độ học'}
        </p>

        {keycloakEnabled && (
          <>
            <button
              type="button"
              className="btn btn-primary btn-block"
              disabled={kcLoading}
              onClick={() => void handleKeycloak()}
            >
              {kcLoading ? 'Đang chuyển tới Keycloak...' : 'Đăng nhập Keycloak'}
            </button>
            <div className="auth-divider">hoặc</div>
          </>
        )}

        <div className="auth-tabs" role="tablist" aria-label="Chọn đăng nhập hoặc đăng ký">
          <button
            type="button"
            role="tab"
            aria-selected={mode === 'login'}
            className={`auth-tab${mode === 'login' ? ' active' : ''}`}
            onClick={() => switchMode('login')}
          >
            Đăng nhập
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={mode === 'register'}
            className={`auth-tab${mode === 'register' ? ' active' : ''}`}
            onClick={() => switchMode('register')}
          >
            Đăng ký
          </button>
        </div>

        <GoogleSignInButton mode={mode} onError={setError} onSuccess={handleGoogleSuccess} />

        {keycloakEnabled && !showDevLogin ? (
          <button
            type="button"
            className="btn btn-ghost btn-block"
            style={{ marginTop: '0.75rem' }}
            onClick={() => setShowDevLogin(true)}
          >
            Dev login (email / mật khẩu)
          </button>
        ) : (
          <>
            <div className="auth-divider">
              {keycloakEnabled ? 'Dev login' : `hoặc dùng email${mode === 'register' ? ' & mật khẩu' : ''}`}
            </div>

            <form onSubmit={handleSubmit} className="auth-form">
              {error && <p className="auth-error">{error}</p>}

              <div className="auth-field">
                <label>
                  Email
                  <input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    autoComplete="email"
                    placeholder="you@example.com"
                    required
                  />
                </label>
              </div>

              <div className="auth-field">
                <label>
                  Mật khẩu
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    autoComplete={mode === 'register' ? 'new-password' : 'current-password'}
                    placeholder="Tối thiểu 8 ký tự"
                    minLength={8}
                    required
                  />
                </label>
              </div>

              <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
                {loading
                  ? 'Đang xử lý...'
                  : mode === 'register'
                    ? 'Tạo tài khoản'
                    : 'Đăng nhập'}
              </button>
            </form>
            {mode === 'login' ? (
              <p className="auth-footer-link" style={{ marginTop: '0.75rem' }}>
                <Link href="/forgot-password">Quên mật khẩu?</Link>
              </p>
            ) : null}
          </>
        )}

        {error && !showDevLogin && <p className="auth-error">{error}</p>}

        <p className="auth-footer-link">
          <Link href="/">← Về trang chủ</Link>
        </p>
      </div>
    </div>
  );
}
