// apps/nihongo-web/src/views/CommunityPage.tsx
'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useQueryClient } from '@tanstack/react-query';
import GroupChatPanel from '@/components/GroupChatPanel';
import VideoCallButton from '@/components/VideoCallButton';
import { useAuth } from '@/hooks/useAuth';
import {
  queryKeys,
  useCommunityOnlineQuery,
  useCommunityRoomQuery,
  useCommunityRoomsQuery,
} from '@/hooks/queries';
import {
  createCommunityGroup,
  createDirectChat,
  searchCommunityUsers,
} from '@/api/index';
import { getStoredToken } from '@/lib/api-client';
import type { CommunityChatUser, CommunityRoomSummary } from '@/types/api';
import '@/components/Community.css';

function formatPreview(iso: string) {
  return new Date(iso).toLocaleString('vi-VN', {
    day: '2-digit',
    month: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export default function CommunityPage() {
  const { isAuthenticated, user } = useAuth();
  const router = useRouter();
  const queryClient = useQueryClient();

  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [searchQ, setSearchQ] = useState('');
  const [searchResults, setSearchResults] = useState<CommunityChatUser[]>([]);
  const [searching, setSearching] = useState(false);
  const [showGroupModal, setShowGroupModal] = useState(false);
  const [groupName, setGroupName] = useState('');
  const [pickedMembers, setPickedMembers] = useState<number[]>([]);
  const [creating, setCreating] = useState(false);

  const { data: rooms, refetch: refetchRooms } = useCommunityRoomsQuery(isAuthenticated);
  const { data: roomDetail, refetch: refetchRoom } = useCommunityRoomQuery(selectedId);
  const { data: onlineUsers } = useCommunityOnlineQuery(isAuthenticated);

  useEffect(() => {
    if (!isAuthenticated) {
      router.replace('/login?redirect=/community');
    }
  }, [isAuthenticated, router]);

  useEffect(() => {
    if (!selectedId && rooms?.length) {
      setSelectedId(rooms[0].id);
    }
  }, [rooms, selectedId]);

  useEffect(() => {
    const q = searchQ.trim();
    if (q.length < 2) {
      setSearchResults([]);
      return;
    }
    const token = getStoredToken();
    if (!token) return;

    const timer = setTimeout(() => {
      setSearching(true);
      void searchCommunityUsers(token, q)
        .then(setSearchResults)
        .finally(() => setSearching(false));
    }, 300);

    return () => clearTimeout(timer);
  }, [searchQ]);

  async function handleDirectChat(targetUserId: number) {
    const token = getStoredToken();
    if (!token) return;
    const res = await createDirectChat(token, targetUserId);
    await queryClient.invalidateQueries({ queryKey: queryKeys.communityRooms });
    setSelectedId(res.room.id);
    setSearchQ('');
    setSearchResults([]);
  }

  async function handleCreateGroup(e: FormEvent) {
    e.preventDefault();
    const token = getStoredToken();
    if (!token || !groupName.trim() || pickedMembers.length === 0) return;
    setCreating(true);
    try {
      const res = await createCommunityGroup(token, groupName.trim(), pickedMembers);
      await queryClient.invalidateQueries({ queryKey: queryKeys.communityRooms });
      setSelectedId(res.room.id);
      setShowGroupModal(false);
      setGroupName('');
      setPickedMembers([]);
    } finally {
      setCreating(false);
    }
  }

  function toggleMember(id: number) {
    setPickedMembers((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id],
    );
  }

  if (!isAuthenticated || !user) {
    return <div className="page-loading">Đang chuyển hướng...</div>;
  }

  const selectedSummary = rooms?.find((r) => r.id === selectedId);
  const directPeer =
    selectedSummary?.type === 'DIRECT'
      ? selectedSummary.members.find((m) => m.id !== user.id)
      : undefined;

  return (
    <div className="container" style={{ padding: '1.5rem 1rem 3rem' }}>
      <p style={{ marginBottom: '1rem' }}>
        <Link href="/">← Trang chủ</Link>
      </p>
      <h1 style={{ marginTop: 0 }}>Cộng đồng học viên</h1>
      <p style={{ color: 'var(--text-secondary)', marginBottom: '1.25rem' }}>
        Nhắn tin nhóm và chat 1:1 với các học viên khác.
      </p>

      <div className="community-layout">
        <aside className="glass-panel community-sidebar">
          <div className="community-toolbar">
            <button
              type="button"
              className="btn btn-primary"
              style={{ flex: 1 }}
              onClick={() => setShowGroupModal(true)}
            >
              + Tạo nhóm
            </button>
            <button
              type="button"
              className="btn btn-outline"
              onClick={() => {
                void refetchRooms();
                if (selectedId) void refetchRoom();
              }}
            >
              ↻
            </button>
          </div>

          <div className="community-online-section">
            <h3>
              <span className="community-online-dot" aria-hidden />
              Đang online ({onlineUsers?.length ?? 0})
            </h3>
            {!onlineUsers?.length && (
              <p className="support-chat-empty" style={{ margin: 0 }}>
                Chưa có ai online. Mở trang này ở tab khác để thử.
              </p>
            )}
            {onlineUsers?.map((u) => (
              <div key={u.id} className="community-user-result">
                <span className="community-online-name">{u.name ?? u.email}</span>
                <div className="community-user-result-actions">
                  <button
                    type="button"
                    className="btn btn-outline"
                    style={{ fontSize: '0.78rem', padding: '0.25rem 0.5rem' }}
                    onClick={() => void handleDirectChat(u.id)}
                  >
                    Chat
                  </button>
                  <VideoCallButton
                    currentUserId={user.id}
                    targetUserId={u.id}
                    compact
                  />
                </div>
              </div>
            ))}
          </div>

          <div className="community-search">
            <input
              type="search"
              placeholder="Tìm học viên (email/tên)..."
              value={searchQ}
              onChange={(e) => setSearchQ(e.target.value)}
            />
            {searching && <p className="support-chat-empty">Đang tìm…</p>}
            {searchResults.map((u) => (
              <div key={u.id} className="community-user-result">
                <span>{u.name ?? u.email}</span>
                <div className="community-user-result-actions">
                  <button
                    type="button"
                    className="btn btn-outline"
                    style={{ fontSize: '0.78rem', padding: '0.25rem 0.5rem' }}
                    onClick={() => void handleDirectChat(u.id)}
                  >
                    Chat
                  </button>
                  <VideoCallButton
                    currentUserId={user.id}
                    targetUserId={u.id}
                    compact
                  />
                </div>
              </div>
            ))}
          </div>

          <h3 style={{ margin: '0 0 0.5rem', fontSize: '0.95rem' }}>Hội thoại</h3>
          {!rooms?.length && <p className="support-chat-empty">Chưa có hội thoại.</p>}
          {rooms?.map((room: CommunityRoomSummary) => (
            <button
              key={room.id}
              type="button"
              className={`community-room-item${selectedId === room.id ? ' community-room-item--active' : ''}`}
              onClick={() => setSelectedId(room.id)}
            >
              <strong>
                {room.type === 'GROUP' ? '👥 ' : '💬 '}
                {room.name}
                {room.unreadCount > 0 && (
                  <span className="community-unread">{room.unreadCount}</span>
                )}
              </strong>
              <span>
                {room.lastMessage?.content ?? 'Chưa có tin nhắn'} ·{' '}
                {formatPreview(room.lastMessageAt)}
              </span>
            </button>
          ))}
        </aside>

        <section>
          <GroupChatPanel
            roomId={selectedId}
            currentUserId={user.id}
            initialMessages={roomDetail?.messages ?? []}
            title={selectedSummary?.name ?? roomDetail?.room.name ?? 'Chat'}
            subtitle={
              selectedSummary?.type === 'GROUP'
                ? `${selectedSummary.members.length} thành viên`
                : 'Chat 1:1'
            }
            headerExtra={
              directPeer ? (
                <VideoCallButton
                  currentUserId={user.id}
                  targetUserId={directPeer.id}
                />
              ) : undefined
            }
            onSent={() => {
              void refetchRooms();
              if (selectedId) void refetchRoom();
            }}
          />
        </section>
      </div>

      {showGroupModal && (
        <div
          className="community-modal-backdrop"
          role="presentation"
          onClick={() => setShowGroupModal(false)}
        >
          <form
            className="glass-panel community-modal"
            onSubmit={(e) => void handleCreateGroup(e)}
            onClick={(e) => e.stopPropagation()}
          >
            <h3>Tạo nhóm mới</h3>
            <label htmlFor="group-name">Tên nhóm</label>
            <input
              id="group-name"
              value={groupName}
              onChange={(e) => setGroupName(e.target.value)}
              placeholder="VD: N5 ôn thi tháng 7"
              required
            />
            <label>Thành viên (tìm ở ô trên sidebar trước)</label>
            <div className="community-member-pick">
              {pickedMembers.length === 0 && (
                <p className="support-chat-empty">Chưa chọn thành viên.</p>
              )}
              {searchResults.map((u) => (
                <label key={u.id}>
                  <input
                    type="checkbox"
                    checked={pickedMembers.includes(u.id)}
                    onChange={() => toggleMember(u.id)}
                  />
                  {u.name ?? u.email}
                </label>
              ))}
            </div>
            <div className="community-modal-actions">
              <button type="button" className="btn btn-outline" onClick={() => setShowGroupModal(false)}>
                Hủy
              </button>
              <button
                type="submit"
                className="btn btn-primary"
                disabled={creating || !groupName.trim() || pickedMembers.length === 0}
              >
                {creating ? 'Đang tạo…' : 'Tạo nhóm'}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}

// apps/nihongo-angular/src/app/features/community/community-page.component.ts
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ApiService } from '../../core/services/api.service';
import { ApiError } from '../../core/http/api-client';
import type {
  CommunityChatUser,
  CommunityRoomSummary,
  GroupChatMessage,
} from '../../core/models/api.models';

const POLL_MS = 5000;

@Component({
  selector: 'app-community-page',
  standalone: true,
  imports: [FormsModule, DatePipe, RouterLink],
  templateUrl: './community-page.component.html',
  styleUrl: './community-page.component.scss',
})
export class CommunityPageComponent {
  private readonly auth = inject(AuthService);
  private readonly api = inject(ApiService);
  private readonly destroyRef = inject(DestroyRef);

  readonly loading = signal(true);
  readonly sending = signal(false);
  readonly error = signal('');
  readonly rooms = signal<CommunityRoomSummary[]>([]);
  readonly selectedRoomId = signal<number | null>(null);
  readonly roomName = signal('');
  readonly messages = signal<GroupChatMessage[]>([]);
  readonly onlineUsers = signal<CommunityChatUser[]>([]);
  readonly searchResults = signal<CommunityChatUser[]>([]);
  readonly searching = signal(false);
  readonly showGroupModal = signal(false);
  readonly creatingGroup = signal(false);
  readonly pickedMembers = signal<number[]>([]);

  draft = '';
  searchQuery = '';
  groupName = '';
  private pollId: ReturnType<typeof setInterval> | null = null;
  private searchTimer: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    this.destroyRef.onDestroy(() => {
      if (this.pollId) clearInterval(this.pollId);
      if (this.searchTimer) clearTimeout(this.searchTimer);
    });
    void this.loadRooms();
  }

  private async loadRooms(): Promise<void> {
    const token = this.auth.token();
    if (!token) {
      this.loading.set(false);
      this.error.set('Đăng nhập để vào cộng đồng.');
      return;
    }

    try {
      const list = await this.api.getCommunityRooms(token);
      this.rooms.set(list);
      void this.loadOnlineUsers();
      if (!this.selectedRoomId() && list.length) {
        this.selectRoom(list[0].id);
      }
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Không tải được phòng chat');
    } finally {
      this.loading.set(false);
    }
  }

  async loadOnlineUsers(): Promise<void> {
    const token = this.auth.token();
    if (!token) return;
    try {
      this.onlineUsers.set(await this.api.getOnlineCommunityUsers(token));
    } catch {
      this.onlineUsers.set([]);
    }
  }

  onSearch(value: string): void {
    this.searchQuery = value;
    if (this.searchTimer) clearTimeout(this.searchTimer);
    if (value.trim().length < 2) {
      this.searchResults.set([]);
      return;
    }
    this.searchTimer = setTimeout(() => void this.searchUsers(value.trim()), 300);
  }

  private async searchUsers(query: string): Promise<void> {
    const token = this.auth.token();
    if (!token) return;
    this.searching.set(true);
    try {
      this.searchResults.set(await this.api.searchCommunityUsers(token, query));
    } finally {
      this.searching.set(false);
    }
  }

  async createDirectChat(userId: number): Promise<void> {
    const token = this.auth.token();
    if (!token) return;
    const result = await this.api.createDirectChat(token, userId);
    await this.loadRooms();
    this.selectRoom(result.id);
    this.searchQuery = '';
    this.searchResults.set([]);
  }

  toggleMember(userId: number): void {
    this.pickedMembers.update((ids) =>
      ids.includes(userId) ? ids.filter((id) => id !== userId) : [...ids, userId],
    );
  }

  async createGroup(): Promise<void> {
    const token = this.auth.token();
    const name = this.groupName.trim();
    if (!token || !name || !this.pickedMembers().length) return;
    this.creatingGroup.set(true);
    try {
      const result = await this.api.createCommunityGroup(token, name, this.pickedMembers());
      await this.loadRooms();
      this.selectRoom(result.id);
      this.showGroupModal.set(false);
      this.groupName = '';
      this.pickedMembers.set([]);
    } finally {
      this.creatingGroup.set(false);
    }
  }

  roomPreview(room: CommunityRoomSummary): string {
    if (!room.lastMessage) return 'Chưa có tin nhắn';
    return typeof room.lastMessage === 'string' ? room.lastMessage : room.lastMessage.content;
  }

  callPath(userId: number): string {
    const current = this.auth.user()?.id ?? 0;
    const lo = Math.min(current, userId);
    const hi = Math.max(current, userId);
    return `/session/${lo * 1_000_000 + hi}/call`;
  }

  directPeer(): CommunityChatUser | undefined {
    const room = this.rooms().find((entry) => entry.id === this.selectedRoomId());
    if (room?.type !== 'DIRECT') return undefined;
    return room.members?.find((member) => member.id !== this.auth.user()?.id);
  }

  selectRoom(roomId: number): void {
    this.selectedRoomId.set(roomId);
    if (this.pollId) clearInterval(this.pollId);
    void this.refreshRoom();
    this.pollId = setInterval(() => void this.refreshRoom(), POLL_MS);
  }

  private async refreshRoom(): Promise<void> {
    const token = this.auth.token();
    const roomId = this.selectedRoomId();
    if (!token || roomId == null) return;

    try {
      const room = await this.api.getCommunityRoom(token, roomId);
      this.roomName.set(room.name);
      this.messages.set(room.messages);
    } catch {
      /* keep last snapshot */
    }
  }

  async send(): Promise<void> {
    const token = this.auth.token();
    const roomId = this.selectedRoomId();
    const text = this.draft.trim();
    if (!token || roomId == null || !text || this.sending()) return;

    this.sending.set(true);
    this.draft = '';

    try {
      await this.api.sendCommunityMessage(token, roomId, text);
      await this.refreshRoom();
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : 'Gửi tin nhắn thất bại');
      this.draft = text;
    } finally {
      this.sending.set(false);
    }
  }

  isMine(msg: GroupChatMessage): boolean {
    return msg.senderId === this.auth.user()?.id;
  }
}

<div class="container" style="padding: 1.5rem 1rem 3rem">
  <p style="margin-bottom: 1rem"><a routerLink="/">← Trang chủ</a></p>
  <h1 style="margin-top: 0">Cộng đồng học viên</h1>
  <p style="color: var(--text-secondary); margin-bottom: 1.25rem">
    Nhắn tin nhóm và chat 1:1 với các học viên khác.
  </p>

  @if (loading()) {
    <div class="glass-panel state-panel">Đang tải phòng…</div>
  } @else if (error() && !rooms().length) {
    <div class="glass-panel state-panel">{{ error() }}</div>
  } @else {
    <div class="community-layout">
      <aside class="glass-panel community-sidebar">
        <div class="community-toolbar">
          <button type="button" class="btn btn-primary" style="flex: 1" (click)="showGroupModal.set(true)">
            + Tạo nhóm
          </button>
          <button type="button" class="btn btn-outline" (click)="loadOnlineUsers()">↻</button>
        </div>

        <div class="community-online-section">
          <h3><span class="community-online-dot"></span> Đang online ({{ onlineUsers().length }})</h3>
          @if (!onlineUsers().length) {
            <p class="support-chat-empty">Chưa có ai online.</p>
          }
          @for (person of onlineUsers(); track person.id) {
            <div class="community-user-result">
              <span class="community-online-name">{{ person.name || person.email }}</span>
              <div class="community-user-result-actions">
                <button type="button" class="btn btn-outline btn-sm" (click)="createDirectChat(person.id)">Chat</button>
                <a [routerLink]="callPath(person.id)" class="btn btn-call btn-call--compact" title="Gọi video">📞</a>
              </div>
            </div>
          }
        </div>

        <div class="community-search">
          <input
            type="search"
            placeholder="Tìm học viên (email/tên)..."
            [value]="searchQuery"
            (input)="onSearch($any($event.target).value)"
          />
          @if (searching()) { <p class="support-chat-empty">Đang tìm…</p> }
          @for (person of searchResults(); track person.id) {
            <div class="community-user-result">
              <span>{{ person.name || person.email }}</span>
              <div class="community-user-result-actions">
                <button type="button" class="btn btn-outline btn-sm" (click)="createDirectChat(person.id)">Chat</button>
                <a [routerLink]="callPath(person.id)" class="btn btn-call btn-call--compact">📞</a>
              </div>
            </div>
          }
        </div>

        <h3 style="margin: 0 0 0.5rem; font-size: 0.95rem">Hội thoại</h3>
        @for (room of rooms(); track room.id) {
          <button
            type="button"
            class="community-room-item"
            [class.community-room-item--active]="room.id === selectedRoomId()"
            (click)="selectRoom(room.id)"
          >
            <strong>
              {{ room.type === 'GROUP' ? '👥' : '💬' }} {{ room.name }}
            @if (room.unreadCount) {
                <span class="community-unread">{{ room.unreadCount }}</span>
            }
            </strong>
            <span>{{ roomPreview(room) }}</span>
          </button>
        }
        @if (!rooms().length) {
          <p class="support-chat-empty">Chưa có hội thoại.</p>
        }
      </aside>

      <section class="support-chat-panel glass-panel">
        @if (selectedRoomId(); as roomId) {
          <header class="support-chat-header">
            <div>
              <h2>{{ roomName() || ('Phòng #' + roomId) }}</h2>
              <p>{{ directPeer() ? 'Chat 1:1' : 'Nhóm học viên' }}</p>
            </div>
            @if (directPeer(); as peer) {
              <a [routerLink]="callPath(peer.id)" class="btn btn-call">📞 Gọi</a>
            }
          </header>

          <div class="support-chat-messages">
            @for (msg of messages(); track msg.id) {
              <div class="support-chat-bubble" [class.support-chat-bubble--mine]="isMine(msg)">
                <strong>{{ msg.senderName ?? 'User' }}</strong>
                <p>{{ msg.content }}</p>
                <time>{{ msg.createdAt | date: 'short' }}</time>
              </div>
            }
            @if (!messages().length) {
              <p class="empty">Chưa có tin nhắn — hãy chào mọi người!</p>
            }
          </div>

          <form class="support-chat-composer" (ngSubmit)="send()">
            <input
              type="text"
              placeholder="Nhập tin nhắn…"
              [(ngModel)]="draft"
              name="draft"
              [disabled]="sending()"
            />
            <button type="submit" class="btn btn-primary" [disabled]="sending() || !draft.trim()">
              Gửi
            </button>
          </form>
        } @else {
          <p class="empty">Chọn một phòng để bắt đầu chat.</p>
        }
      </section>
    </div>
  }

  @if (showGroupModal()) {
    <div class="community-modal-backdrop" (click)="showGroupModal.set(false)">
      <form class="glass-panel community-modal" (ngSubmit)="createGroup()" (click)="$event.stopPropagation()">
        <h3>Tạo nhóm mới</h3>
        <label>
          Tên nhóm
          <input [(ngModel)]="groupName" name="groupName" placeholder="VD: N5 ôn thi tháng 7" required />
        </label>
        <label>Thành viên (tìm ở ô sidebar trước)</label>
        <div class="community-member-pick">
          @if (!searchResults().length) {
            <p class="support-chat-empty">Tìm học viên ở ô sidebar rồi chọn thành viên.</p>
          }
          @for (person of searchResults(); track person.id) {
            <label>
              <input
                type="checkbox"
                [checked]="pickedMembers().includes(person.id)"
                (change)="toggleMember(person.id)"
              />
              {{ person.name || person.email }}
            </label>
          }
        </div>
        <div class="community-modal-actions">
          <button type="button" class="btn btn-outline" (click)="showGroupModal.set(false)">Hủy</button>
          <button
            type="submit"
            class="btn btn-primary"
            [disabled]="creatingGroup() || !groupName.trim() || !pickedMembers().length"
          >
            {{ creatingGroup() ? 'Đang tạo…' : 'Tạo nhóm' }}
          </button>
        </div>
      </form>
    </div>
  }
</div>
