// apps/nihongo-web/src/components/GoogleSignInButton.tsx
'use client';

import { GoogleLogin } from '@react-oauth/google';
import { useAuth } from '@/hooks/useAuth';
import { ApiError } from '@/types/api';

type GoogleSignInButtonProps = {
  mode?: 'login' | 'register';
  onError?: (message: string) => void;
  onSuccess?: (role: string) => void;
};

export default function GoogleSignInButton({
  mode = 'login',
  onError,
  onSuccess,
}: GoogleSignInButtonProps) {
  const { loginWithGoogle } = useAuth();
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

  if (!clientId) {
    return (
      <p className="auth-google-hint">
        <strong>Đăng ký bằng Gmail</strong> chưa bật. Tạo OAuth Client ID tại{' '}
        <a href="https://console.cloud.google.com/apis/credentials" target="_blank" rel="noreferrer">
          Google Cloud Console
        </a>
        , rồi thêm <code>NEXT_PUBLIC_GOOGLE_CLIENT_ID</code> vào{' '}
        <code>apps/nihongo-web/.env</code> và <code>GOOGLE_CLIENT_ID</code> vào{' '}
        <code>services/.env</code>. Xem <code>docs/google-oauth-setup.md</code>.
      </p>
    );
  }

  const googleText = mode === 'register' ? 'signup_with' : 'continue_with';

  return (
    <div className="auth-google-wrap">
      <GoogleLogin
        onSuccess={async (res) => {
          if (!res.credential) {
            onError?.('Không nhận được token từ Google');
            return;
          }
          try {
            const authUser = await loginWithGoogle(res.credential);
            onSuccess?.(authUser.role);
          } catch (err) {
            onError?.(
              err instanceof ApiError ? err.message : err instanceof Error ? err.message : 'Google đăng nhập thất bại',
            );
          }
        }}
        onError={() => onError?.('Google đăng nhập bị hủy hoặc lỗi')}
        text={googleText}
        shape="rectangular"
        theme="outline"
        size="large"
        width="360"
        locale="vi"
      />
    </div>
  );
}

// apps/nihongo-angular/src/app/shared/google-sign-in-button/google-sign-in-button.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  inject,
  signal,
} from '@angular/core';
import { AuthService } from '../../core/services/auth.service';
import { ApiError } from '../../core/http/api-client';

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: Record<string, unknown>) => void;
          renderButton: (parent: HTMLElement, config: Record<string, unknown>) => void;
        };
      };
    };
  }
}

@Component({
  selector: 'app-google-sign-in-button',
  standalone: true,
  template: `
    @if (clientId()) {
      <div class="auth-google-wrap">
        <div #buttonHost></div>
      </div>
    } @else {
      <p class="auth-google-hint">
        <strong>Đăng ký bằng Gmail</strong> chưa bật. Thêm
        <code>&lt;meta name="google-signin-client_id" content="..."&gt;</code>
        vào <code>index.html</code> hoặc dùng email + mật khẩu bên dưới.
      </p>
    }
  `,
})
export class GoogleSignInButtonComponent implements AfterViewInit {
  @Input() mode: 'login' | 'register' = 'login';
  @Output() googleError = new EventEmitter<string>();
  @Output() googleSuccess = new EventEmitter<string>();

  private readonly auth = inject(AuthService);
  readonly clientId = signal('');

  @ViewChild('buttonHost') private buttonHost?: ElementRef<HTMLDivElement>;

  ngAfterViewInit(): void {
    const meta = document.querySelector('meta[name="google-signin-client_id"]');
    const id = meta?.getAttribute('content')?.trim() ?? '';
    if (!id) return;

    this.clientId.set(id);
    void this.loadScript().then(() => this.renderButton(id));
  }

  private loadScript(): Promise<void> {
    if (window.google?.accounts?.id) return Promise.resolve();

    return new Promise((resolve, reject) => {
      const existing = document.querySelector('script[data-google-gsi]');
      if (existing) {
        existing.addEventListener('load', () => resolve());
        existing.addEventListener('error', () => reject(new Error('Google script failed')));
        return;
      }

      const script = document.createElement('script');
      script.src = 'https://accounts.google.com/gsi/client';
      script.async = true;
      script.defer = true;
      script.dataset['googleGsi'] = '1';
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Google script failed'));
      document.head.appendChild(script);
    });
  }

  private renderButton(clientId: string): void {
    const host = this.buttonHost?.nativeElement;
    if (!host || !window.google?.accounts?.id) return;

    window.google.accounts.id.initialize({
      client_id: clientId,
      callback: (response: { credential?: string }) => {
        void this.handleCredential(response.credential);
      },
    });

    window.google.accounts.id.renderButton(host, {
      type: 'standard',
      theme: 'outline',
      size: 'large',
      text: this.mode === 'register' ? 'signup_with' : 'continue_with',
      shape: 'rectangular',
      width: 360,
      locale: 'vi',
    });
  }

  private async handleCredential(credential?: string): Promise<void> {
    if (!credential) {
      this.googleError.emit('Không nhận được token từ Google');
      return;
    }

    try {
      const user = await this.auth.loginWithGoogle(credential);
      this.googleSuccess.emit(user.role);
    } catch (err) {
      this.googleError.emit(
        err instanceof ApiError
          ? err.message
          : err instanceof Error
            ? err.message
            : 'Google đăng nhập thất bại',
      );
    }
  }
}
